/*
    The worked example for `code.patches`, and the run that checks the
    declarative path reproduces D89's hand-written one.

    `mod.json` says which script, which offset and what is expected there;
    `bleck` generates the guard and the write. This file supplies only the hook
    the patched instruction calls, plus a report block so the outcome is
    readable from outside.

    Report block, big-endian u32:

      +0x00  magic 'PTCH'
      +0x04  he1_01 initScript pointer
      +0x08  bleck_patch_status[0]  1 pending, 2 applied, 3 refused, 4 no script
      +0x0C  word 0, read back after the patch ran
      +0x10  word 1, read back after the patch ran
      +0x14  times the hook was entered
      +0x18  sentinel, written by the hook
      +0x1C  SEQ_GAME frames
      +0x20  bleck_patch_count

    Run with:  scripts/ingame.py evt-patch --map he1_01 --words 12
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x50544348U /* 'PTCH' */
#define SENTINEL 0xB1ECB1ECU
#define MAP_INIT_OFFSET 0x18
#define SEQ_COUNT 6
#define SEQ_GAME 2

/* What the evt VM expects back so the script advances (D89). */
#define EVT_CONTINUE 2

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define SCRIPT (probe[1])
#define STATUS (probe[2])
#define BACK_W0 (probe[3])
#define BACK_W1 (probe[4])
#define HOOK_HITS (probe[5])
#define HOOK_MARK (probe[6])
#define GAME_FRAMES (probe[7])
#define PATCH_COUNT (probe[8])

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];
extern void *mapDataPtr(const char *name);

/* Generated by bleck from `code.patches`. */
extern u32 bleck_patch_status[];
extern const u32 bleck_patch_count;

static const char target[] = "he1_01";

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Called by the patched script. evt's user-func signature. */
s32 on_he1_init(void *entry, int firstRun)
{
    (void) entry;
    (void) firstRun;

    HOOK_HITS += 1;
    HOOK_MARK = SENTINEL;
    return EVT_CONTINUE;
}

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    unsigned char *data;
    u32 *script = 0;
    u32 i;

    for (i = 0; i < 12; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    /* bleck applies patches before calling this, so the status is final and
       the words below are what the VM will read. */
    STATUS = bleck_patch_status[0];
    PATCH_COUNT = bleck_patch_count;

    data = (unsigned char *) mapDataPtr(target);
    if (data != 0)
        script = *(u32 **) (data + MAP_INIT_OFFSET);
    SCRIPT = (u32) script;
    if (script != 0)
    {
        BACK_W0 = script[0];
        BACK_W1 = script[1];
    }

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
