/*
    The worked example for `item:` patches, and for a replacement wider than
    two words.

    Item 0x41's use script opens with `USER_FUNC f, a, b, c` -- argc 4, five
    words (D91). bleck replaces it with a USER_FUNC of the same argc, so word 0
    becomes 0x0004005C, word 1 becomes this file's hook, and words 2..4 are the
    original's own arguments, untouched.

    WHAT THIS CAN AND CANNOT SHOW UNATTENDED.
      it can: the selector resolved, the guard matched the real instruction,
              the words changed to what was intended, and the game still runs.
      it cannot: that the hook is ever *entered*. An item use script only runs
              when the player uses that item, which needs menu navigation, and
              controller input cannot be injected (D48). HOOK_HITS therefore
              reads 0 on an unattended run and that says nothing either way.

    WARNING: item scripts are shared -- 22 distinct scripts across the 33 table
    entries. SHARED reports how many entries point at the one patched here.

    Report block, big-endian u32:

      +0x00  magic 'ITPT'
      +0x04  itemEventDataTable[0].useScript, the script this id resolves to
      +0x08  bleck_patch_status[0]  1 pending 2 applied 3 refused 4 no script
                                    5 id not in the table
      +0x0C  bleck_patch_shared[0]  entries pointing at that script
      +0x10  word 0, read back after the patch ran
      +0x14  word 1, read back
      +0x18  word 2, read back  -- carried through, must be unchanged
      +0x1C  word 3, read back  -- carried through, must be unchanged
      +0x20  word 4, read back  -- carried through, must be unchanged
      +0x24  times the hook was entered (0 unattended; see above)
      +0x28  sentinel, written by the hook
      +0x2C  SEQ_GAME frames
      +0x30  the id this mod asked for, as the table reports it

    Run with:  scripts/ingame.py item-patch --words 14
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x49545054U /* 'ITPT' */
#define SENTINEL 0xB1ECB1ECU

#define SEQ_COUNT 6
#define SEQ_GAME 2

#define ITEM_COUNT 33
#define WANTED_ID 0x41
#define REPORT_WORDS 14

/* What the evt VM expects back so the script advances (D89). */
#define EVT_CONTINUE 2

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

typedef struct
{
    s32 itemId;
    u32 *useScript;
    const char *useMsgName;
} ItemEventData;

extern SeqDef seq_data[];
extern ItemEventData itemEventDataTable[];

/* Generated by bleck from `code.patches`. */
extern u32 bleck_patch_status[];
extern u32 bleck_patch_shared[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define SCRIPT (probe[1])
#define STATUS (probe[2])
#define SHARED (probe[3])
#define BACK(i) (probe[4 + (i)])
#define HOOK_HITS (probe[9])
#define HOOK_MARK (probe[10])
#define GAME_FRAMES (probe[11])
#define FOUND_ID (probe[12])

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Called by the patched script. evt's user-func signature.

   The original's arguments are still in the instruction, so they reach here the
   way any user func's do: entry->pCurData (spm/evtmgr.h +0x14) points at the
   argument words and entry->curDataLength (+0x09) counts them. */
s32 on_item_use(void *entry, int firstRun)
{
    (void) entry;
    (void) firstRun;

    HOOK_HITS += 1;
    HOOK_MARK = SENTINEL;
    return EVT_CONTINUE;
}

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    u32 *script = 0;
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    /* bleck applies patches before calling this, so the status is final and
       the words below are what the VM would read. */
    STATUS = bleck_patch_status[0];
    SHARED = bleck_patch_shared[0];

    /* Resolved independently of the generated code, so a wrong lookup and a
       wrong write do not look the same. */
    for (i = 0; i < ITEM_COUNT; i++)
        if (itemEventDataTable[i].itemId == WANTED_ID)
        {
            FOUND_ID = (u32) itemEventDataTable[i].itemId;
            script = itemEventDataTable[i].useScript;
            break;
        }
    SCRIPT = (u32) script;
    if (script != 0)
        for (i = 0; i < 5; i++)
            BACK(i) = script[i];

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
