/*
    Is `evt_door_set_door_descs` called at all, and with what?

    D91 said doors need intercepting that function; D93 ruled out the cheap
    route (it is not called from any map's init script) and left the question
    open. Stage 1 (`mods/code-patch-probe`) proved a branch written at run time
    takes effect once the caches are flushed. This puts the two together on
    live game code.

    Both hooks are branch *replacements*, not trampolines: the original body
    never runs. So while this mod is loaded the map's doors are not registered
    and its NPCs are not drawn. That is acceptable for a probe and is the whole
    reason it is a separate mod.

    THE CONTROL, and why there is one. A hook that records 0 entries is
    ambiguous -- broken hook, or never called. So a function that is definitely
    called is patched the same way in the same run. If the control counts
    entries and the door setter does not, that is a fact about doors. If
    neither does, it is a fact about the hook.

    The control is `npcDispMain` (`spm/npcdrv.h`, `void npcDispMain()`): the
    NPC display pass, no arguments, no return value, and drawing cannot gate a
    sequence transition. It also fires only once a map is *live*, so a non-zero
    count says gameplay in mac_01 was actually reached -- which is the second
    thing this run has to establish.

    RULED OUT: the first attempt used `effMain` instead. It counted 104,419 entries,
    proving the mechanism outright, and **hung the map change**: the game sat
    in SEQ_MAPCHANGE for 90 s and never reached gameplay, so the door count of
    0 was truncation, not absence (D94). Do not stub the effect driver.

    `evt_door_set_door_descs` is declared as an evt user func
    (`EVT_DECLARE_USER_FUNC(..., 1)`), so a caller through the VM would pass
    (EvtEntry *, bool) and expect 2 back. A caller in a map's own REL would
    pass (DoorDesc *, s32). The hook records both registers and probes the
    first as if it were an EvtEntry, so the two can be told apart; it returns 2
    so an evt caller advances rather than spinning forever.

    Report block, big-endian u32:

      +0x00  magic 'DHOK'
      +0x04  door hook install status   0 ok 1 misaligned 2 out of range
      +0x08  control hook install status
      +0x0C  door setter entries
      +0x10  control entries
      +0x14  door r3, first entry
      +0x18  door r4, first entry
      +0x1C  word at r3 + 0x00
      +0x20  word at r3 + 0x08   (EvtEntry flags/curDataLength/curOpcode)
      +0x24  word at r3 + 0x14   (EvtEntry.pCurData)
      +0x28  door r3, most recent entry
      +0x2C  door r4, most recent entry
      +0x30  first instruction of evt_door_set_door_descs, read back
      +0x34  first instruction of npcDispMain, read back
      +0x38  &doorHook
      +0x3C  &controlHook
      +0x40  SEQ_GAME frames
      +0x44  map changes seen
      +0x48  SEQ_MAPCHANGE frames

    Run with:  scripts/ingame.py door-hook-probe --map mac_01 --words 20
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x44484F4BU /* 'DHOK' */
#define REPORT_WORDS 20

#define SEQ_COUNT 6
#define SEQ_GAME 2
#define SEQ_MAPCHANGE 3

/* What the evt VM expects back so a calling script advances (D89). */
#define EVT_CONTINUE 2

/* Generated by bleck. See runtime_c.CODE_PATCH. */
extern s32 bleck_code_hook(void *at, const void *to);

/* Bound by elf2rel against the symbol list; no address appears here. */
extern void evt_door_set_door_descs(void);
extern void npcDispMain(void);

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define DOOR_STATUS (probe[1])
#define CTRL_STATUS (probe[2])
#define DOOR_HITS (probe[3])
#define CTRL_HITS (probe[4])
#define DOOR_A0 (probe[5])
#define DOOR_A1 (probe[6])
#define DOOR_W0 (probe[7])
#define DOOR_W2 (probe[8])
#define DOOR_W5 (probe[9])
#define DOOR_LAST_A0 (probe[10])
#define DOOR_LAST_A1 (probe[11])
#define DOOR_READ (probe[12])
#define CTRL_READ (probe[13])
#define DOOR_HOOK_AT (probe[14])
#define CTRL_HOOK_AT (probe[15])
#define GAME_FRAMES (probe[16])
#define MAP_CHANGES (probe[17])
#define CHANGE_FRAMES (probe[18])

/* EvtEntry, if that is what r3 is: +0x08 packs flags, curDataLength and
   curOpcode; +0x14 is pCurData (spm/evtmgr.h). */
#define EVT_STATE_WORD 2
#define EVT_CUR_DATA_WORD 5

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/*
    Replaces `evt_door_set_door_descs` entirely. `a0`/`a1` are whatever the
    caller left in r3/r4, which is the point: nothing here assumes which of the
    two calling conventions is in use.
*/
s32 doorHook(void *a0, s32 a1)
{
    const u32 *fields = (const u32 *) a0;

    DOOR_HITS += 1;
    DOOR_LAST_A0 = (u32) a0;
    DOOR_LAST_A1 = (u32) a1;

    if (DOOR_HITS == 1)
    {
        DOOR_A0 = (u32) a0;
        DOOR_A1 = (u32) a1;
        if (fields != 0)
        {
            DOOR_W0 = fields[0];
            DOOR_W2 = fields[EVT_STATE_WORD];
            DOOR_W5 = fields[EVT_CUR_DATA_WORD];
        }
    }
    return EVT_CONTINUE;
}

/* Replaces `npcDispMain`. Counting is all it has to do. */
void controlHook(void)
{
    CTRL_HITS += 1;
}

static u32 lastSeq = 0xFFFFFFFFU;

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;
    if (seq == SEQ_MAPCHANGE)
    {
        CHANGE_FRAMES += 1;
        if (lastSeq != SEQ_MAPCHANGE)
            MAP_CHANGES += 1;
    }
    lastSeq = seq;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    DOOR_HOOK_AT = (u32) doorHook;
    CTRL_HOOK_AT = (u32) controlHook;

    DOOR_STATUS = (u32) bleck_code_hook((void *) evt_door_set_door_descs,
                                        (const void *) doorHook);
    CTRL_STATUS =
        (u32) bleck_code_hook((void *) npcDispMain, (const void *) controlHook);

    DOOR_READ = *(volatile u32 *) evt_door_set_door_descs;
    CTRL_READ = *(volatile u32 *) npcDispMain;

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
