/*
    The worked example for `code.patches`, and the run that checks the
    declarative path reproduces D89's hand-written one.

    `mod.json` says which script, which offset and what is expected there;
    `bleck` generates the guard and the write. This file supplies only the hook
    the patched instruction calls, plus a report block so the outcome is
    readable from outside.

    Report block, big-endian u32:

      +0x00  magic 'PTCH'
      +0x04  he1_01 initScript pointer
      +0x08  bleck_patch_status[0]  1 pending 2 applied 3 refused 4 no script
                                    5 id not in the table
      +0x0C  word 0, read back after the patch ran
      +0x10  word 1, read back after the patch ran
      +0x14  times the hook was entered
      +0x18  sentinel, written by the hook
      +0x1C  SEQ_GAME frames
      +0x20  bleck_patch_count
      +0x24  bleck_patch_shared[0]  (UNCOUNTED 0xFFFFFFFF for a map patch)
      +0x28  entry->pCurData, captured by the hook
      +0x2C  entry->pCurData[0]
      +0x30  the u32 at entry+0x08: flags, curDataLength, curOpcode, priority

    The last three answer where a hook's arguments live: this instruction is
    argc 1 at word 0, so pCurData is either the function-pointer word
    (script + 4) or the word after it (script + 8). Nothing else discriminates.

    Run with:  scripts/ingame.py evt-patch --map he1_01 --words 14
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x50544348U /* 'PTCH' */
#define SENTINEL 0xB1ECB1ECU
#define MAP_INIT_OFFSET 0x18
#define SEQ_COUNT 6
#define SEQ_GAME 2

/* What the evt VM expects back so the script advances (D89). */
#define EVT_CONTINUE 2

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define SCRIPT (probe[1])
#define STATUS (probe[2])
#define BACK_W0 (probe[3])
#define BACK_W1 (probe[4])
#define HOOK_HITS (probe[5])
#define HOOK_MARK (probe[6])
#define GAME_FRAMES (probe[7])
#define PATCH_COUNT (probe[8])
#define SHARED (probe[9])
#define CUR_DATA (probe[10])
#define CUR_DATA_0 (probe[11])
#define ENTRY_STATE (probe[12])

#define REPORT_WORDS 14

/* spm/evtmgr.h: EvtEntry.pCurData is +0x14, so word 5. The byte at +0x09 is
   curDataLength; read as a word alongside flags, curOpcode and priority. */
#define EVT_CUR_DATA_WORD 5
#define EVT_STATE_WORD 2

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];
extern void *mapDataPtr(const char *name);

/* Generated by bleck from `code.patches`. */
extern u32 bleck_patch_status[];
extern u32 bleck_patch_shared[];
extern const u32 bleck_patch_count;

static const char target[] = "he1_01";

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Called by the patched script. evt's user-func signature. */
s32 on_he1_init(void *entry, int firstRun)
{
    const u32 *fields = (const u32 *) entry;

    (void) firstRun;

    HOOK_HITS += 1;
    HOOK_MARK = SENTINEL;
    if (entry != 0)
    {
        CUR_DATA = fields[EVT_CUR_DATA_WORD];
        ENTRY_STATE = fields[EVT_STATE_WORD];
        if (CUR_DATA != 0)
            CUR_DATA_0 = *(const u32 *) CUR_DATA;
    }
    return EVT_CONTINUE;
}

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    unsigned char *data;
    u32 *script = 0;
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    /* bleck applies patches before calling this, so the status is final and
       the words below are what the VM will read. */
    STATUS = bleck_patch_status[0];
    SHARED = bleck_patch_shared[0];
    PATCH_COUNT = bleck_patch_count;

    data = (unsigned char *) mapDataPtr(target);
    if (data != 0)
        script = *(u32 **) (data + MAP_INIT_OFFSET);
    SCRIPT = (u32) script;
    if (script != 0)
    {
        BACK_W0 = script[0];
        BACK_W1 = script[1];
    }

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
