/*
    Does writing a PowerPC instruction at run time actually take effect?

    D93 left interception of `evt_door_set_door_descs` as the only route to
    door descriptors, and it needs a capability bleck did not have: writing a
    branch at a live address. This measures that mechanism on *this module's
    own code*, where a mistake cannot hurt the game.

    Two identical experiments, differing only in the cache flush:

      pair A   store the branch, do NOT flush   (bleck_code_store)
      pair B   store the branch AND flush       (bleck_code_hook)

    Both pairs are called once *before* the write, so the old body is in the
    instruction cache when the store lands -- otherwise the no-flush case is
    not adversarial and proves nothing. Separate function pairs, so one case
    cannot contaminate the other.

    If both work, the flush was never tested here; that is a finding about
    Dolphin, not about the Wii.

    A third check refuses an out-of-range branch: masking a 256 MB
    displacement would emit a valid branch somewhere else entirely.

    Report block, big-endian u32:

      +0x00  magic 'CODE'
      +0x04  pair A encode status   0 ok 1 misaligned 2 out of range
      +0x08  pair A encoded word
      +0x0C  pair A return, before the store
      +0x10  pair A return, after the store with NO flush
      +0x14  pair A first instruction, read back
      +0x18  pair B hook status
      +0x1C  pair B encoded word
      +0x20  pair B return, before the write
      +0x24  pair B return, after the write WITH flush
      +0x28  pair B first instruction, read back
      +0x2C  out-of-range status, must be 2
      +0x30  the scratch word the refused hook must NOT have written
      +0x34  &pairAFrom
      +0x38  &pairATo
      +0x3C  &pairBFrom
      +0x40  &pairBTo
      +0x44  SEQ_GAME frames
      +0x48  what pairATo returns, for comparison
      +0x4C  what pairBTo returns, for comparison

    Run with:  scripts/ingame.py code-patch-probe --words 20
    Target: eu0. Nothing here writes to game memory.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x434F4445U /* 'CODE' */
#define REPORT_WORDS 20

#define SEQ_COUNT 6
#define SEQ_GAME 2

/* Distinct enough that a report word says which body ran. */
#define A_FROM_VALUE 0xA11A0000U
#define A_TO_VALUE 0xA22A0000U
#define B_FROM_VALUE 0xB11B0000U
#define B_TO_VALUE 0xB22B0000U

#define SCRATCH_VALUE 0xDEADBEEFU
/* Far enough from anywhere in MEM1 that the displacement cannot fit. */
#define FAR_TARGET 0x90000000U

#define BLECK_CODE_RANGE 2

/* Generated by bleck. See runtime_c.CODE_PATCH. */
extern void bleck_code_store(void *at, u32 word);
extern s32 bleck_code_branch(const void *from, const void *to, u32 *out);
extern s32 bleck_code_hook(void *at, const void *to);

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define A_STATUS (probe[1])
#define A_ENC (probe[2])
#define A_BEFORE (probe[3])
#define A_AFTER (probe[4])
#define A_READ (probe[5])
#define B_STATUS (probe[6])
#define B_ENC (probe[7])
#define B_BEFORE (probe[8])
#define B_AFTER (probe[9])
#define B_READ (probe[10])
#define R_STATUS (probe[11])
#define R_SCRATCH (probe[12])
#define A_FROM_AT (probe[13])
#define A_TO_AT (probe[14])
#define B_FROM_AT (probe[15])
#define B_TO_AT (probe[16])
#define GAME_FRAMES (probe[17])
#define A_TO_SAYS (probe[18])
#define B_TO_SAYS (probe[19])

typedef u32(Probed)(void);

/*
    `noinline` and `noclone` keep the bodies as real functions, and every call
    goes through a *volatile* pointer so the optimiser cannot fold the return
    value at the call site -- which would make a patched jump invisible.
    Checked against the disassembly of what was actually built, not assumed.
*/
#define PROBED __attribute__((noinline, noclone))

static PROBED u32 pairAFrom(void) { return A_FROM_VALUE; }
static PROBED u32 pairATo(void) { return A_TO_VALUE; }
static PROBED u32 pairBFrom(void) { return B_FROM_VALUE; }
static PROBED u32 pairBTo(void) { return B_TO_VALUE; }

static Probed *volatile callA = pairAFrom;
static Probed *volatile callB = pairBFrom;
static Probed *volatile callATo = pairATo;
static Probed *volatile callBTo = pairBTo;

static volatile u32 scratch = SCRATCH_VALUE;

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Pair A: store the branch and do not flush. */
static void runNoFlush(void)
{
    u32 word = 0;

    A_BEFORE = callA();
    A_STATUS = (u32) bleck_code_branch((void *) pairAFrom, (void *) pairATo, &word);
    A_ENC = word;
    if (A_STATUS == 0)
        bleck_code_store((void *) pairAFrom, word);
    A_AFTER = callA();
    A_READ = *(volatile u32 *) pairAFrom;
}

/* Pair B: the same write, with dcbst/sync/icbi/isync. */
static void runFlushed(void)
{
    u32 word = 0;

    B_BEFORE = callB();
    bleck_code_branch((void *) pairBFrom, (void *) pairBTo, &word);
    B_ENC = word;
    B_STATUS = (u32) bleck_code_hook((void *) pairBFrom, (void *) pairBTo);
    B_AFTER = callB();
    B_READ = *(volatile u32 *) pairBFrom;
}

/* The refusal, exercised rather than reasoned about. */
static void runOutOfRange(void)
{
    R_STATUS = (u32) bleck_code_hook((void *) &scratch, (const void *) FAR_TARGET);
    R_SCRATCH = scratch;
}

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    A_FROM_AT = (u32) pairAFrom;
    A_TO_AT = (u32) pairATo;
    B_FROM_AT = (u32) pairBFrom;
    B_TO_AT = (u32) pairBTo;
    /* Read through the same volatile pointers, so a patched pair is still
       comparable against what the destination body returns. */
    A_TO_SAYS = callATo();
    B_TO_SAYS = callBTo();

    runNoFlush();
    runFlushed();
    runOutOfRange();

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
