"""What a script is allowed to call, and how many arguments it takes.

Until now `bleck` accepted any name in a call and let `elf2rel` fail at link
time with "Missing 1 required symbol(s)". That is a poor place to find a typo:
it happens after the compiler has run, it needs a symbol list and a toolchain,
and it says nothing about what you *should* have written. Worse, it cannot
catch a wrong argument count at all — `evt_pouch_add_coins()` with no arguments
links fine and then misbehaves in-game.

So `bleck` carries a catalog of the game's script builtins: name, argument
count, and the documented signature. It is used for three things — validating
calls before anything is compiled, suggesting a correction when a name is
close, and letting `bleck script builtins` answer "what can I even call?".

Where the data comes from
-------------------------
Extracted from the `EVT_DECLARE_USER_FUNC` / `EVT_UNKNOWN_USER_FUNC`
declarations in `spm-headers`, which is MIT. `bleck script index` regenerates
the catalog from a checkout; the generated file records its provenance.

Named `catalog` rather than `builtins`, which would shadow the standard
library module of that name.

⚠️ The catalog describes what the *headers* document, which is not the same as
what a given game version can link. Coverage varies sharply by version, so a
name in the catalog can still fail at link time on `kr0`. The catalog is
therefore advisory for existence and authoritative for arity.
"""

from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

#: Shipped catalog, generated by `bleck script index`.
CATALOG_FILE = Path(__file__).parent / "catalog.json"

#: Recorded in the generated file. The names and argument counts are extracted
#: from MIT-licensed headers, and saying so where the data lives costs nothing
#: and keeps the provenance attached to the artifact rather than only to a
#: commit message.
ATTRIBUTION = (
    "Function names and argument counts extracted from SeekyCt/spm-headers, "
    "MIT licensed (https://github.com/SeekyCt/spm-headers). "
    "Regenerate with `bleck script index <path-to-spm-headers/include>`."
)

#: `EVT_DECLARE_USER_FUNC(name, argc)` and `EVT_UNKNOWN_USER_FUNC(name)`.
_DECLARED = re.compile(r"EVT_DECLARE_USER_FUNC\(\s*(\w+)\s*,\s*(-?\d+)\s*\)")
_UNKNOWN = re.compile(r"EVT_UNKNOWN_USER_FUNC\(\s*(\w+)\s*\)")

#: A signature comment looks like `// evt_mario_set_pos(f32 x, f32 y, f32 z)`.
#: Matched against the function's own name so unrelated prose above a
#: declaration is not mistaken for one.
_SIGNATURE = re.compile(r"^//\s*(\w+\s*\(.*)$")


@dataclass(frozen=True)
class Builtin:
    """One callable game function, as the headers describe it."""

    name: str
    module: str
    """Header it was declared in, e.g. `evt_mario`."""

    arity: int | None = None
    """Declared argument count, or None when upstream does not know it.

    Upstream writes -1 for variadic and uses a separate macro for "no idea";
    both collapse to None here, because neither can be checked.
    """

    signature: str = ""
    """The documented signature, when a comment gives one."""

    @property
    def is_documented(self) -> bool:
        return self.arity is not None

    def describe(self) -> str:
        """One line for `bleck script builtins`.

        Upstream documents a full signature for only about a third of these, so
        the fallback has to say something useful about the rest rather than
        printing an empty parameter list that looks like "takes nothing".
        """
        if self.signature:
            return self.signature
        if self.arity is None:
            return f"{self.name}(?)          argument count undocumented"
        if self.arity == 0:
            return f"{self.name}()"
        plural = "" if self.arity == 1 else "s"
        return f"{self.name}(...)        {self.arity} argument{plural}"


@dataclass(frozen=True)
class Catalog:
    """Every builtin `bleck` knows about."""

    builtins: list[Builtin]
    source: str = ""
    """Where the catalog was generated from, for provenance."""

    by_name: dict[str, Builtin] = field(default_factory=dict, repr=False, compare=False)
    """Name lookup, filled in on construction. Excluded from equality."""

    def __post_init__(self) -> None:
        # Mutating the dict is fine on a frozen dataclass; rebinding is not.
        self.by_name.update({b.name: b for b in self.builtins})

    @property
    def names(self) -> list[str]:
        return [b.name for b in self.builtins]

    def find(self, name: str) -> Builtin | None:
        return self.by_name.get(name)

    def search(self, term: str) -> list[Builtin]:
        """Builtins whose name or signature mentions `term`, case-insensitively."""
        needle = term.lower()
        return [
            b
            for b in self.builtins
            if needle in b.name.lower() or needle in b.signature.lower()
        ]

    def suggest(self, name: str, limit: int = 3) -> list[str]:
        """Close names, for a did-you-mean.

        Cutoff is deliberately high: a wrong suggestion is worse than none,
        because it sends the reader looking for a function that is not the one
        they wanted.
        """
        return difflib.get_close_matches(name, self.names, n=limit, cutoff=0.75)

    def to_json(self) -> str:
        body = {
            "attribution": ATTRIBUTION,
            "source": self.source,
            "builtins": [
                {
                    "name": b.name,
                    "module": b.module,
                    "arity": b.arity,
                    "signature": b.signature,
                }
                for b in sorted(self.builtins, key=lambda b: b.name)
            ],
        }
        return json.dumps(body, indent=1) + "\n"

    @classmethod
    def from_json(cls, text: str) -> Catalog:
        raw = json.loads(text)
        return cls(
            builtins=[
                Builtin(
                    name=entry["name"],
                    module=entry.get("module", ""),
                    arity=entry.get("arity"),
                    signature=entry.get("signature", ""),
                )
                for entry in raw.get("builtins", [])
            ],
            source=raw.get("source", ""),
        )


def parse_header(text: str, module: str) -> list[Builtin]:
    """Pull every user-func declaration out of one header."""
    found: list[Builtin] = []
    lines = text.splitlines()

    for number, line in enumerate(lines):
        declared = _DECLARED.search(line)
        unknown = None if declared else _UNKNOWN.search(line)
        if not declared and not unknown:
            continue

        name = (declared or unknown).group(1)
        arity: int | None = None
        if declared:
            value = int(declared.group(2))
            # -1 is upstream's "variadic or unknown"; not checkable either way.
            arity = None if value < 0 else value

        found.append(
            Builtin(
                name=name,
                module=module,
                arity=arity,
                signature=_signature_above(lines, number, name),
            )
        )
    return found


def _signature_above(lines: list[str], index: int, name: str) -> str:
    """Find the `// name(...)` comment in the block above a declaration.

    Scans the contiguous comment block rather than only the line immediately
    above, because upstream often puts prose between the signature and the
    declaration.
    """
    for offset in range(index - 1, max(index - 6, -1), -1):
        stripped = lines[offset].strip()
        if not stripped.startswith("//"):
            break
        match = _SIGNATURE.match(stripped)
        if match and match.group(1).startswith(name):
            return match.group(1).strip()
    return ""


def build_catalog(include: Path) -> Catalog:
    """Scan a `spm-headers` include tree for builtin declarations."""
    headers = sorted(include.rglob("*.h"))
    if not headers:
        raise FileNotFoundError(f"no headers under {include}")

    builtins: list[Builtin] = []
    seen: set[str] = set()
    for header in headers:
        for builtin in parse_header(header.read_text(encoding="utf-8"), header.stem):
            if builtin.name in seen:
                continue
            seen.add(builtin.name)
            builtins.append(builtin)

    return Catalog(
        builtins=sorted(builtins, key=lambda b: b.name),
        source=f"{len(headers)} headers, {len(builtins)} builtins",
    )


_LOADED: Catalog | None = None


def load() -> Catalog:
    """The shipped catalog. Empty if it has not been generated."""
    global _LOADED  # pylint: disable=global-statement
    if _LOADED is None:
        if CATALOG_FILE.exists():
            _LOADED = Catalog.from_json(CATALOG_FILE.read_text(encoding="utf-8"))
        else:
            _LOADED = Catalog(builtins=[])
    return _LOADED
