"""What a script is allowed to call, and how many arguments it takes.

Name, arity and documented signature for the game's script builtins, used to
validate calls before compiling, suggest corrections, and answer `bleck script
builtins`. Extracted from the `EVT_DECLARE_USER_FUNC` /
`EVT_UNKNOWN_USER_FUNC` declarations in MIT-licensed `spm-headers`; `bleck
script index` regenerates it from a checkout.

⚠️ The catalog describes what the *headers* document, not what a given game
version can link — a listed name can still fail to link on `kr0`. Advisory for
existence, authoritative for arity.
"""

from __future__ import annotations

import difflib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

#: Shipped catalog, generated by `bleck script index`.
CATALOG_FILE = Path(__file__).parent / "catalog.json"

#: Recorded in the generated file so provenance travels with the data.
#:
#: ⚠️ **The MIT notice is here in full, not as a link.** This catalog is derived
#: data that `bleck` ships, so the licence's "included in all copies or
#: substantial portions" applies to it -- and a URL is not the notice. See
#: `THIRD-PARTY-NOTICES.md`.
ATTRIBUTION = (
    "Function names and argument counts extracted from the MIT-licensed "
    "portions of SeekyCt/spm-headers (https://github.com/SeekyCt/spm-headers). "
    "Regenerate with `bleck script index <path-to-spm-headers/include>`."
)

#: The notice `spm-headers`' MIT licence requires to travel with derived data.
UPSTREAM_NOTICE = (
    "MIT License. Copyright (c) 2022 Seeky. Permission is hereby granted, free "
    "of charge, to any person obtaining a copy of this software and associated "
    'documentation files (the "Software"), to deal in the Software without '
    "restriction, including without limitation the rights to use, copy, modify, "
    "merge, publish, distribute, sublicense, and/or sell copies of the Software, "
    "and to permit persons to whom the Software is furnished to do so, subject "
    "to the following conditions: The above copyright notice and this permission "
    "notice shall be included in all copies or substantial portions of the "
    'Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, '
    "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF "
    "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN "
    "NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, "
    "DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR "
    "OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE "
    "USE OR OTHER DEALINGS IN THE SOFTWARE."
)

#: `EVT_DECLARE_USER_FUNC(name, argc)` and `EVT_UNKNOWN_USER_FUNC(name)`.
_DECLARED = re.compile(r"EVT_DECLARE_USER_FUNC\(\s*(\w+)\s*,\s*(-?\d+)\s*\)")
_UNKNOWN = re.compile(r"EVT_UNKNOWN_USER_FUNC\(\s*(\w+)\s*\)")

#: A signature comment looks like `// evt_mario_set_pos(f32 x, f32 y, f32 z)`.
_SIGNATURE = re.compile(r"^//\s*(\w+\s*\(.*)$")


@dataclass(frozen=True)
class Builtin:
    """One callable game function, as the headers describe it."""

    name: str
    module: str
    """Header it was declared in, e.g. `evt_mario`."""

    arity: int | None = None
    """Declared argument count. None covers both upstream's -1 (variadic) and
    its "unknown" macro, since neither can be checked."""

    signature: str = ""
    """The documented signature, when a comment gives one."""

    @property
    def is_documented(self) -> bool:
        return self.arity is not None

    def describe(self) -> str:
        """One line for `bleck script builtins`.

        Only about a third have a documented signature, so the fallback must
        not print an empty parameter list that reads as "takes nothing".
        """
        if self.signature:
            return self.signature
        if self.arity is None:
            return f"{self.name}(?)          argument count undocumented"
        if self.arity == 0:
            return f"{self.name}()"
        plural = "" if self.arity == 1 else "s"
        return f"{self.name}(...)        {self.arity} argument{plural}"


@dataclass(frozen=True)
class Catalog:
    """Every builtin `bleck` knows about."""

    builtins: list[Builtin]
    source: str = ""
    """Where the catalog was generated from, for provenance."""

    by_name: dict[str, Builtin] = field(default_factory=dict, repr=False, compare=False)
    """Name lookup, filled in on construction. Excluded from equality."""

    def __post_init__(self) -> None:
        # Mutating the dict is fine on a frozen dataclass; rebinding is not.
        self.by_name.update({b.name: b for b in self.builtins})

    @property
    def names(self) -> list[str]:
        return [b.name for b in self.builtins]

    def find(self, name: str) -> Builtin | None:
        return self.by_name.get(name)

    def search(self, term: str) -> list[Builtin]:
        """Builtins whose name or signature mentions `term`, case-insensitively."""
        needle = term.lower()
        return [
            b
            for b in self.builtins
            if needle in b.name.lower() or needle in b.signature.lower()
        ]

    def suggest(self, name: str, limit: int = 3) -> list[str]:
        """Close names, for a did-you-mean. High cutoff: a wrong suggestion is
        worse than none."""
        return difflib.get_close_matches(name, self.names, n=limit, cutoff=0.75)

    def to_json(self) -> str:
        body = {
            "attribution": ATTRIBUTION,
            "upstream_license": UPSTREAM_NOTICE,
            "source": self.source,
            "builtins": [
                {
                    "name": b.name,
                    "module": b.module,
                    "arity": b.arity,
                    "signature": b.signature,
                }
                for b in sorted(self.builtins, key=lambda b: b.name)
            ],
        }
        return json.dumps(body, indent=1) + "\n"

    @classmethod
    def from_json(cls, text: str) -> Catalog:
        raw = json.loads(text)
        return cls(
            builtins=[
                Builtin(
                    name=entry["name"],
                    module=entry.get("module", ""),
                    arity=entry.get("arity"),
                    signature=entry.get("signature", ""),
                )
                for entry in raw.get("builtins", [])
            ],
            source=raw.get("source", ""),
        )


def parse_header(text: str, module: str) -> list[Builtin]:
    """Pull every user-func declaration out of one header."""
    found: list[Builtin] = []
    lines = text.splitlines()

    for number, line in enumerate(lines):
        declared = _DECLARED.search(line)
        unknown = None if declared else _UNKNOWN.search(line)
        if not declared and not unknown:
            continue

        name = (declared or unknown).group(1)
        arity: int | None = None
        if declared:
            value = int(declared.group(2))
            # -1 is upstream's "variadic or unknown"; not checkable either way.
            arity = None if value < 0 else value

        found.append(
            Builtin(
                name=name,
                module=module,
                arity=arity,
                signature=_signature_above(lines, number, name),
            )
        )
    return found


def _signature_above(lines: list[str], index: int, name: str) -> str:
    """Find the `// name(...)` comment in the block above a declaration.

    Scans the whole contiguous comment block: upstream often puts prose between
    the signature and the declaration.
    """
    for offset in range(index - 1, max(index - 6, -1), -1):
        stripped = lines[offset].strip()
        if not stripped.startswith("//"):
            break
        match = _SIGNATURE.match(stripped)
        if match and match.group(1).startswith(name):
            return match.group(1).strip()
    return ""


def build_catalog(include: Path) -> Catalog:
    """Scan a `spm-headers` include tree for builtin declarations."""
    headers = sorted(include.rglob("*.h"))
    if not headers:
        raise FileNotFoundError(f"no headers under {include}")

    builtins: list[Builtin] = []
    seen: set[str] = set()
    for header in headers:
        for builtin in parse_header(header.read_text(encoding="utf-8"), header.stem):
            if builtin.name in seen:
                continue
            seen.add(builtin.name)
            builtins.append(builtin)

    return Catalog(
        builtins=sorted(builtins, key=lambda b: b.name),
        source=f"{len(headers)} headers, {len(builtins)} builtins",
    )


_LOADED: Catalog | None = None


def load() -> Catalog:
    """The shipped catalog. Empty if it has not been generated."""
    global _LOADED  # pylint: disable=global-statement
    if _LOADED is None:
        if CATALOG_FILE.exists():
            _LOADED = Catalog.from_json(CATALOG_FILE.read_text(encoding="utf-8"))
        else:
            _LOADED = Catalog(builtins=[])
    return _LOADED
