"""Writing compiled scripts out as C, for the existing REL toolchain to build.

Generating C rather than an object file directly is what lets this reuse the
whole proven path — devkitPPC, the relocatable link, `pyelf2rel` — instead of
becoming a second, parallel code generator that has to learn ELF and PowerPC
relocations by itself.

It also solves the address problem cleanly. Scripts refer to game functions by
name; the generated C declares them `extern` and takes their address, and
`elf2rel` binds each one through the symbol list at REL-build time. So no game
address is ever written by `bleck`, and no symbol list has to be redistributed
with it.
"""

from __future__ import annotations

from dataclasses import dataclass

from bleck.script.compiler import (
    CompiledProgram,
    CompiledScript,
    Literal,
    ScriptWord,
    StringWord,
    SymbolWord,
    Word,
)
from bleck.script.errors import Position, ScriptError

#: The script the loader starts. Chosen by name rather than by position so that
#: reordering a file cannot silently change which script runs.
ENTRY_SCRIPT = "main"

#: The game's sequences, in order (spm/seqdrv.h). A name's index is both the
#: value the game puts in `seqWork.seq` and the row it uses in `seq_data[]`.
SEQUENCE_NAMES = ("logo", "title", "game", "mapchange", "gameover", "load")

#: Where the banner is drawn unless a mod says otherwise. The title screen is
#: where someone checks which disc they are running.
DEFAULT_BANNER_SEQUENCES = ("title",)

_PREFIX = "bleck_"

_HEADER = """\
/*
    Generated by `bleck` from {origin}.
    Do not edit: rebuild the script instead.

    This is an evt script module. The arrays below are bytecode for Super Paper
    Mario's own script VM. `_prolog` hooks the game's sequence table; the entry
    script is handed to the scheduler when gameplay starts, and re-started after
    anything that resets evt state, such as a map change.

    Game functions are referenced by name and resolved by `elf2rel` against a
    symbol list, so no addresses appear here.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;
"""

#: Defined in every generated module, so a mod's own C can run at load time
#: without owning `_prolog` itself. Weak, so a mod that supplies its own
#: strong definition overrides this empty one at link time.
MOD_HOOK = """/*
    A mod's own C may define `mod_prolog` to run when the module loads.

    This is a weak *definition* rather than a declaration, and the difference
    matters: a weak declaration leaves an undefined symbol, and `elf2rel` tries
    to resolve every undefined symbol against the game's list. `mod_prolog` is
    not a game function, so a script-only mod failed to build with
    "Missing 1 required symbol(s): mod_prolog". Defining it here means there is
    nothing left undefined, and a mod that supplies its own strong definition
    overrides this one at link time.

    `_prolog` stays owned by the generated code because it has to install the
    sequence hooks first -- see the comment below for why that ordering matters.

    Anything touching live engine state belongs in a sequence hook, not here:
    at load time the game is barely up. docs/hook-points.md has the timings.
*/
__attribute__((weak)) void mod_prolog(void)
{
}
"""


#: Everything that needs a per-frame hook on the game's sequence table. Shared
#: by scripts (which need re-arming) and the banner (which needs drawing), so
#: a mod using both installs one set of hooks, not two.
_SEQ_TABLE = """
typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

/* Resolved by name from the symbol list, like everything else here. */
extern SeqDef seq_data[];

/* spm/seqdrv.h: LOGO 0, TITLE 1, GAME 2, MAPCHANGE 3, GAMEOVER 4, LOAD 5 */
#define BLECK_SEQ_COUNT 6
#define BLECK_SEQ_GAME 2

/*
    Deliberately initialised to non-zero values so these land in .data rather
    than .bss. The loader allocates this module's bss but nothing documents
    whether it zeroes it, and depending on that would be a silent hazard.
*/
static SeqFunc *bleck_real_main[BLECK_SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};
"""

_SEQ_INSTALL = """
static void bleck_seq0(void *w) {{ bleck_after_seq(0, w); }}
static void bleck_seq1(void *w) {{ bleck_after_seq(1, w); }}
static void bleck_seq2(void *w) {{ bleck_after_seq(2, w); }}
static void bleck_seq3(void *w) {{ bleck_after_seq(3, w); }}
static void bleck_seq4(void *w) {{ bleck_after_seq(4, w); }}
static void bleck_seq5(void *w) {{ bleck_after_seq(5, w); }}

static SeqFunc *const bleck_hooks[BLECK_SEQ_COUNT] = {{
    bleck_seq0, bleck_seq1, bleck_seq2,
    bleck_seq3, bleck_seq4, bleck_seq5,
}};

void _prolog(void)
{{
    u32 i;

    for (i = 0; i < BLECK_SEQ_COUNT; i++)
    {{
        bleck_real_main[i] = seq_data[i].main;
        seq_data[i].main = bleck_hooks[i];
    }}

    mod_prolog();
}}
"""

#: For a mod with neither a script nor a banner: nothing to hook, so `_prolog`
#: does one thing.
_PLAIN_PROLOG = """
void _prolog(void)
{
    mod_prolog();
}
"""

_ENTRY_POINTS = """
void _epilog(void)
{
}

void _unresolved(void)
{
}
"""

_SCRIPT_COMMENT = """
/*
    Starting the script, and keeping it started.

    `_prolog` runs the instant the loader links this module, far too early to
    hand anything to the script scheduler: the evt manager is not initialised
    yet, so `evtEntry` there does nothing at all. Hooking
    `seq_data[SEQ_GAME].init` does not work either. Both were measured, not
    guessed -- D38 and D40.

    What does work is `seq_data[SEQ_GAME].main`, verified by reading the running
    game's memory from outside the emulator: the script is created and then runs
    once per frame (D43).

    The second half is less obvious. **A script does not survive a map change** --
    evt state is torn down and rebuilt, and a script started once simply stops,
    which was measured the same way. So rather than starting once, every
    sequence other than gameplay re-arms a flag and gameplay starts the script
    whenever it is armed. That covers map changes, game overs and loads without
    needing to know which of them resets evt.
*/

static u32 bleck_needs_start = 1;
"""

_SCRIPT_BODY = """    if (seq == BLECK_SEQ_GAME)
    {{
        if (bleck_needs_start)
        {{
            bleck_needs_start = 0;
            evtEntry({entry}, 0, 0);
        }}
    }}
    else
    {{
        bleck_needs_start = 1;
    }}
"""

#: The on-screen label naming the loaded mod.
#:
#: Every call here mirrors `spm-rel-loader`'s title-screen example, which is the
#: only known-working use of this API: start, style, measure, draw -- and draw
#: *before* delegating to the real sequence main.
_BANNER_BLOCK = """
/*
    Naming the loaded mod on screen.

    Text is drawn in screen space, which is centred with y increasing upward:
    `spm-rel-loader` centres a string with `x = -(width / 2)` and places it near
    the top of the title screen with `y = 200`. So the visible area is roughly
    x -320..320 and y -240..240, and the bottom-right corner is (+320, -240).
    The margins below back off from that corner far enough to survive overscan.

    `FontGetMessageWidth` measures the string so it can be right-aligned rather
    than positioned by guesswork, which also keeps a long mod name on screen.
*/

extern void FontDrawStart(void);
extern void FontDrawEdge(void);
extern void FontDrawColor(u8 *color);
extern void FontDrawScale(float scale);
extern void FontDrawNoiseOff(void);
extern void FontDrawRainbowColorOff(void);
extern void FontDrawString(float x, float y, const char *text);
extern unsigned short FontGetMessageWidth(const char *text);

#define BLECK_BANNER_RIGHT 296.0f
#define BLECK_BANNER_BOTTOM (-200.0f)
#define BLECK_BANNER_SCALE 0.6f

static const char bleck_banner_text[] = {text};

/* wii/gx.h GXColor, four bytes. Not const: FontDrawColor overwrites alpha. */
static u8 bleck_banner_color[4] = {{255, 255, 255, 255}};

/* Which sequences draw it. .rodata, so the loader's bss handling is moot. */
static const u8 bleck_banner_on[BLECK_SEQ_COUNT] = {{{flags}}};

static void bleck_draw_banner(void)
{{
    float width;

    FontDrawStart();
    FontDrawEdge();
    FontDrawColor(bleck_banner_color);
    FontDrawScale(BLECK_BANNER_SCALE);
    FontDrawNoiseOff();
    FontDrawRainbowColorOff();

    width = (float) FontGetMessageWidth(bleck_banner_text) * BLECK_BANNER_SCALE;
    FontDrawString(BLECK_BANNER_RIGHT - width, BLECK_BANNER_BOTTOM,
                   bleck_banner_text);
}}
"""

_BANNER_BODY = """    if (bleck_banner_on[seq])
        bleck_draw_banner();
"""


@dataclass(frozen=True)
class Banner:
    """An on-screen label naming the mod that is loaded.

    A disc looks identical to a stock one until something visibly differs, so a
    player juggling several builds has no way to tell which is in the drive.
    This draws the answer on the screen.
    """

    text: str
    sequences: tuple[int, ...] = (1,)
    """Sequence indices to draw on. Defaults to the title screen."""

    @property
    def flags(self) -> str:
        """The `sequences` set rendered as a C initialiser, one flag per row."""
        on = set(self.sequences)
        return ", ".join(
            "1" if index in on else "0" for index in range(len(SEQUENCE_NAMES))
        )


@dataclass(frozen=True)
class GeneratedSource:
    """C source for a compiled program, plus what it needs from the linker."""

    text: str
    entry_script: str
    external_symbols: list[str]

    @property
    def line_count(self) -> int:
        return len(self.text.splitlines())


def _c_string(text: str) -> str:
    """Escape a Python string as a C string literal.

    Non-ASCII is escaped byte-wise from UTF-8 rather than emitted raw, so the
    generated file stays pure ASCII and cannot be re-encoded by an editor into
    something the compiler reads differently.
    """
    out = ""
    for byte in text.encode("utf-8"):
        char = chr(byte)
        if char == "\\":
            out += "\\\\"
        elif char == '"':
            out += '\\"'
        elif char == "\n":
            out += "\\n"
        elif char == "\t":
            out += "\\t"
        elif char == "\r":
            out += "\\r"
        elif 0x20 <= byte < 0x7F:
            out += char
        else:
            # Octal, not hex: a hex escape in C consumes every following hex
            # digit, so "\x41" followed by a literal 'B' would parse as one
            # oversized escape. Octal is capped at three digits.
            out += f"\\{byte:03o}"
    return f'"{out}"'


def _word_text(word: Word) -> str:
    if isinstance(word, Literal):
        return str(word.value)
    if isinstance(word, SymbolWord):
        return f"(s32) &{word.name}"
    if isinstance(word, StringWord):
        return f"(s32) {_PREFIX}string_{word.index}"
    if isinstance(word, ScriptWord):
        return f"(s32) {_PREFIX}script_{word.name}"
    raise TypeError(f"unknown word type {type(word).__name__}")


def _script_array(script: CompiledScript) -> str:
    lines = [
        f"/* {script.name}: {len(script.words)} words, "
        f"{script.slots_used} of 16 local slots used */",
        f"const s32 {_PREFIX}script_{script.name}[] = {{",
    ]
    # Four per line: enough to be compact, few enough that a diff points at a
    # small region when bytecode changes.
    row: list[str] = []
    for word in script.words:
        row.append(_word_text(word))
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def _footer(entry: str, banner: Banner | None) -> str:
    """Assemble the scaffolding that runs the mod, from the pieces it needs.

    A script needs a per-frame hook to start and re-start it; so does a banner,
    to draw it. When both are present they share one set of hooks rather than
    installing two layers of them.
    """
    if entry == "" and banner is None:
        return _PLAIN_PROLOG + _ENTRY_POINTS

    parts = [_SEQ_TABLE]
    body = ""

    if banner is not None:
        parts.append(
            _BANNER_BLOCK.format(text=_c_string(banner.text), flags=banner.flags)
        )
        body += _BANNER_BODY

    if entry:
        parts.append(_SCRIPT_COMMENT)
        body += ("\n" if body else "") + _SCRIPT_BODY.format(entry=entry)

    parts.append(
        "\nstatic void bleck_after_seq(u32 seq, void *work)\n"
        "{\n"
        f"{body}\n"
        "    if (bleck_real_main[seq] != 0)\n"
        "        bleck_real_main[seq](work);\n"
        "}\n"
    )
    parts.append(_SEQ_INSTALL.format())
    parts.append(_ENTRY_POINTS)
    return "".join(parts)


def generate_bare(
    origin: str = "native sources", banner: Banner | None = None
) -> GeneratedSource:
    """Scaffolding for a mod that ships only native C.

    The REL format still needs its three entry points, and the mod still needs
    somewhere to be called from, but there is no script to schedule.
    """
    text = _HEADER.format(origin=origin) + "\n" + MOD_HOOK + _footer("", banner)
    _require_ascii(text)
    return GeneratedSource(text=text, entry_script="", external_symbols=[])


def generate(
    program: CompiledProgram,
    origin: str = "a script",
    banner: Banner | None = None,
) -> GeneratedSource:
    """Render a compiled program as a single C translation unit."""
    entry = _entry_script(program)

    parts = [_HEADER.format(origin=origin)]

    if program.called_symbols:
        parts.append(
            "/* Game functions called by USER_FUNC, bound by elf2rel. */\n"
            + "\n".join(f"extern void {name}(void);" for name in program.called_symbols)
        )

    parts.append(
        "/* Started by the game's script scheduler. */\n"
        "extern void *evtEntry(const s32 *script, u32 priority, u8 flags);"
    )
    parts.append(MOD_HOOK)

    if program.strings:
        parts.append(
            "\n".join(
                f"static const char {_PREFIX}string_{index}[] = {_c_string(text)};"
                for index, text in enumerate(program.strings)
            )
        )

    if len(program.scripts) > 1:
        # Scripts may spawn each other in any order, so every array is declared
        # before any is defined.
        parts.append(
            "\n".join(
                f"extern const s32 {_PREFIX}script_{script.name}[];"
                for script in program.scripts
            )
        )

    parts.extend(_script_array(script) for script in program.scripts)
    parts.append(_footer(f"{_PREFIX}script_{entry}", banner))

    text = "\n\n".join(parts)
    _require_ascii(text)
    return GeneratedSource(
        text=text,
        entry_script=entry,
        external_symbols=list(program.called_symbols),
    )


def _require_ascii(text: str) -> None:
    """Guard the invariant that generated C is pure ASCII.

    Mods get built on Linux, macOS and Windows, whose compilers and editors do
    not agree on a default source encoding. String contents are already escaped
    byte-wise, so the only way a non-ASCII character reaches here is a comment
    template in this module -- which is a `bleck` bug, and better caught during
    generation than as a mojibake comment in someone else's build log.
    """
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        raise ValueError(
            f"generated C contains non-ASCII {offending!r}; "
            "this is a bug in bleck's code templates"
        ) from exc


def _entry_script(program: CompiledProgram) -> str:
    names = [script.name for script in program.scripts]
    if ENTRY_SCRIPT in names:
        return ENTRY_SCRIPT
    listed = ", ".join(names)
    raise ScriptError(
        f"no script named {ENTRY_SCRIPT!r} to start "
        f"(this file declares: {listed}). "
        f"Rename one to {ENTRY_SCRIPT!r}, or spawn the others from it",
        Position(),
    )
