"""Writing compiled scripts out as C, for the existing REL toolchain to build.

Generating C rather than an object file directly is what lets this reuse the
whole proven path — devkitPPC, the relocatable link, `pyelf2rel` — instead of
becoming a second, parallel code generator that has to learn ELF and PowerPC
relocations by itself.

It also solves the address problem cleanly. Scripts refer to game functions by
name; the generated C declares them `extern` and takes their address, and
`elf2rel` binds each one through the symbol list at REL-build time. So no game
address is ever written by `bleck`, and no symbol list has to be redistributed
with it.
"""

from __future__ import annotations

import difflib
from dataclasses import dataclass, field

from bleck.script.compiler import (
    CompiledProgram,
    CompiledScript,
    Literal,
    ScriptWord,
    StringWord,
    SymbolWord,
    Word,
)
from bleck.script.errors import Position, ScriptError

#: The script the loader starts. Chosen by name rather than by position so that
#: reordering a file cannot silently change which script runs.
ENTRY_SCRIPT = "main"

#: The game's sequences, in order (spm/seqdrv.h). A name's index is both the
#: value the game puts in `seqWork.seq` and the row it uses in `seq_data[]`.
SEQUENCE_NAMES = ("logo", "title", "game", "mapchange", "gameover", "load")

#: Where the banner is drawn unless a mod says otherwise. The title screen is
#: where someone checks which disc they are running.
DEFAULT_BANNER_SEQUENCES = ("title",)

#: The script a `code.boot` declaration is desugared into.
#:
#: Named rather than anonymous so it appears in `bleck mod build` output like
#: any other script, and so a collision with a mod's own script is a plain
#: duplicate-name error instead of a mystery.
BOOT_SCRIPT = "bleck_boot"

#: How long the boot script waits before asking for the map change.
#:
#: Two seconds. The first map has only just finished loading and the sequence
#: that loaded it is still unwinding; requesting another change immediately is
#: the shape of thing that deadlocked the map loader in D51. This is the value
#: `mods/goto-map` proved works (D52), kept rather than tuned downward — the
#: whole point of booting into a map is that nobody is watching, so two seconds
#: costs nothing and a deadlock costs a run.
BOOT_DELAY_FRAMES = 120

_PREFIX = "bleck_"

_HEADER = """\
/*
    Generated by `bleck` from {origin}.
    Do not edit: rebuild the script instead.

    This is an evt script module. The arrays below are bytecode for Super Paper
    Mario's own script VM. `_prolog` hooks the game's sequence table; the entry
    script is handed to the scheduler when gameplay starts, and re-started after
    anything that resets evt state, such as a map change.

    Game functions are referenced by name and resolved by `elf2rel` against a
    symbol list, so no addresses appear here.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;
"""

#: Defined in every generated module, so a mod's own C can run at load time
#: without owning `_prolog` itself. Weak, so a mod that supplies its own
#: strong definition overrides this empty one at link time.
MOD_HOOK = """/*
    A mod's own C may define `mod_prolog` to run when the module loads.

    This is a weak *definition* rather than a declaration, and the difference
    matters: a weak declaration leaves an undefined symbol, and `elf2rel` tries
    to resolve every undefined symbol against the game's list. `mod_prolog` is
    not a game function, so a script-only mod failed to build with
    "Missing 1 required symbol(s): mod_prolog". Defining it here means there is
    nothing left undefined, and a mod that supplies its own strong definition
    overrides this one at link time.

    `_prolog` stays owned by the generated code because it has to install the
    sequence hooks first -- see the comment below for why that ordering matters.

    Anything touching live engine state belongs in a sequence hook, not here:
    at load time the game is barely up. docs/hook-points.md has the timings.
*/
__attribute__((weak)) void mod_prolog(void)
{
}
"""


#: Running a script when a named map is reached.
#:
#: ⛔ This does *not* patch `MapData.initScript`, which was the obvious design
#: and does not work: it deadlocks the map loader (D51). Instead the sequence
#: hook watches where the game says it is going, and starts the script once
#: gameplay resumes -- both mechanisms already verified in D43.
_MAP_BLOCK = """
/*
    Map hooks.

    The game announces where it is going: during a map change, `seqWork.p0`
    holds the destination map's name. So arriving somewhere is observable
    without touching the game's own data at all -- the sequence hook notes the
    name on the way in, and starts the script once gameplay resumes.

    RULED OUT: patching `MapData.initScript` to chain the map's own script.
    It deadlocks -- the load freezes partway and never completes, whether the
    original is spawned blocking or detached. Measured, not guessed; see D51.

    Both halves of what is used instead are already proven: `evtEntry` from
    `seq_data[SEQ_GAME].main` is exactly how every bleck script starts (D43),
    and reading `seqWork.p0` during a map change is how the destination was
    identified in the first place (D47).
*/

typedef struct
{{
    s32 seq;
    s32 stage;
    const char *p0;
    const char *p1;
}} SeqWork;

extern SeqWork seqWork;

#define BLECK_SEQ_MAPCHANGE 3
#define BLECK_MAP_COUNT {count}
{tables}
static const char *const bleck_map_names[BLECK_MAP_COUNT] = {{
{name_list}}};

static const s32 *const bleck_map_scripts[BLECK_MAP_COUNT] = {{
{script_list}}};

/*
    Which maps are waiting to start, one bit each. Set while the map change is
    still in flight and consumed when gameplay resumes, because that is the
    moment evt is alive again -- a script started during the change would be
    torn down with the rest of evt state.
*/
static u32 bleck_map_pending = 0;

/* By hand: the module links -nostdlib, so there is no strcmp to call. */
static u32 bleck_same_name(const char *a, const char *b)
{{
    u32 i;

    if (a == 0 || b == 0)
        return 0;
    for (i = 0; a[i] != 0; i++)
        if (a[i] != b[i])
            return 0;
    return b[i] == 0;
}}

static void bleck_maps_on_seq(u32 seq)
{{
    u32 i;

    if (seq == BLECK_SEQ_MAPCHANGE)
    {{
        for (i = 0; i < BLECK_MAP_COUNT; i++)
            if (bleck_same_name(seqWork.p0, bleck_map_names[i]))
                bleck_map_pending |= (1 << i);
        return;
    }}

    if (seq != BLECK_SEQ_GAME || bleck_map_pending == 0)
        return;

    for (i = 0; i < BLECK_MAP_COUNT; i++)
    {{
        if (bleck_map_pending & (1 << i))
        {{
            bleck_map_pending &= ~(1 << i);
            evtEntry(bleck_map_scripts[i], 0, 0);
        }}
    }}
}}
"""

#: One map's name. The script it starts is referenced by the table below.
_MAP_TABLE = """
static const char {prefix}name_{index}[] = {name};
"""

#: The on-screen label naming the loaded mod.
#:
#: Every call mirrors `spm-rel-loader`'s title-screen example, which is the only
#: known-working use of this API: start, style, measure, draw -- and draw
#: *before* delegating to the real sequence main.
_BANNER_BLOCK = """
/*
    Naming the loaded mod on screen.

    Text is drawn in screen space, which is centred with y increasing upward:
    `spm-rel-loader` centres a string with `x = -(width / 2)` and places it near
    the top of the title screen with `y = 200`. So the visible area is roughly
    x -320..320 and y -240..240, and the bottom-right corner is (+320, -240).
    The margins below back off from that corner far enough to survive overscan.

    `FontGetMessageWidth` measures the string so it can be right-aligned rather
    than positioned by guesswork, which also keeps a long mod name on screen.
*/

extern void FontDrawStart(void);
extern void FontDrawEdge(void);
extern void FontDrawColor(u8 *color);
extern void FontDrawScale(float scale);
extern void FontDrawNoiseOff(void);
extern void FontDrawRainbowColorOff(void);
extern void FontDrawString(float x, float y, const char *text);
extern unsigned short FontGetMessageWidth(const char *text);

#define BLECK_BANNER_RIGHT 296.0f
#define BLECK_BANNER_BOTTOM (-200.0f)
#define BLECK_BANNER_SCALE 0.6f

static const char bleck_banner_text[] = {text};

/* wii/gx.h GXColor, four bytes. Not const: FontDrawColor overwrites alpha. */
static u8 bleck_banner_color[4] = {{255, 255, 255, 255}};

/* Which sequences draw it. .rodata, so the loader's bss handling is moot. */
static const u8 bleck_banner_on[BLECK_SEQ_COUNT] = {{{flags}}};

static void bleck_draw_banner(void)
{{
    float width;

    FontDrawStart();
    FontDrawEdge();
    FontDrawColor(bleck_banner_color);
    FontDrawScale(BLECK_BANNER_SCALE);
    FontDrawNoiseOff();
    FontDrawRainbowColorOff();

    width = (float) FontGetMessageWidth(bleck_banner_text) * BLECK_BANNER_SCALE;
    FontDrawString(BLECK_BANNER_RIGHT - width, BLECK_BANNER_BOTTOM,
                   bleck_banner_text);
}}
"""

#: Typedefs and the saved originals. Needed by anything wanting a per-frame
#: hook -- a free-running script, a map watcher, or both.
_SEQ_TABLE = """
/*
    Hooking the game's sequence table.

    `_prolog` runs the instant the loader links this module, far too early to
    hand anything to the script scheduler: the evt manager is not initialised
    yet, so `evtEntry` there does nothing at all. Hooking
    `seq_data[SEQ_GAME].init` does not work either. Both were measured, not
    guessed -- D38 and D40.

    What does work is `seq_data[SEQ_GAME].main`, verified by reading the running
    game's memory from outside the emulator: the script is created and then runs
    once per frame (D43).
*/

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

/* Resolved by name from the symbol list, like everything else here. */
extern SeqDef seq_data[];

/* spm/seqdrv.h: LOGO 0, TITLE 1, GAME 2, MAPCHANGE 3, GAMEOVER 4, LOAD 5 */
#define BLECK_SEQ_COUNT 6
#define BLECK_SEQ_GAME 2

/*
    Deliberately initialised to non-zero values so these land in .data rather
    than .bss. The loader allocates this module's bss but nothing documents
    whether it zeroes it, and depending on that would be a silent hazard.
*/
static SeqFunc *bleck_real_main[BLECK_SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};
"""

#: Starting the entry script, and keeping it started.
_SCRIPT_START = """
/*
    A script does not survive a map change (D43). evt state is torn down and
    rebuilt, and a script started once simply stops. So rather than starting
    once, every sequence other than gameplay re-arms a flag and gameplay starts
    the script whenever it is armed. That covers map changes, game overs and
    loads without needing to know which of them resets evt.
*/

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{
    if (seq != BLECK_SEQ_GAME)
    {
        bleck_needs_start = 1;
        return;
    }
    if (bleck_needs_start)
    {
        bleck_needs_start = 0;
        evtEntry(%s, 0, 0);
    }
}
"""

#: Booting straight into a chosen map.
#:
#: Deliberately *not* a re-armed hook like `_SCRIPT_START`: this fires once, on
#: the first frame of gameplay, and never again. Re-arming it would send the
#: game back to the same map every time it left, which is a loop rather than a
#: starting point.
_BOOT_BLOCK = """
/*
    Booting into a map.

    An unattended boot reaches exactly two maps -- aa4_01 then ls4_12, the
    attract demo -- and controller input cannot be injected (D48), so every
    other map used to need a human. This starts a script on the first frame of
    gameplay that asks the game to go somewhere else instead (D52).

    Note what this does *not* do: it does not try to redirect the first map
    load, which would be faster. The game is asked to change maps through its
    own `evt_seq_mapchange`, exactly as a door would, so arriving here is the
    same arrival the game performs everywhere else. Overwriting `seqWork.p0`
    before the loader reads it is the obvious shortcut and is untested; D51 is
    what happens when the map loader is handed something it did not expect.

    `bleck_boot_pending` starts at 1 rather than 0 so it lands in .data. The
    loader allocates this module's bss but nothing documents whether it zeroes
    it, and a boot map that fired only on some builds would be a miserable bug.
*/

static u32 bleck_boot_pending = 1;

static void bleck_boot_on_seq(u32 seq)
{{
    if (seq != BLECK_SEQ_GAME || bleck_boot_pending == 0)
        return;
    bleck_boot_pending = 0;
    evtEntry({script}, 0, 0);
}}
"""

#: Starting a script when a button combination is pressed.
#:
#: The reading path is measured, not assumed: `wpadGetWork()` is at `0x8023697c`
#: in the eu0 lst, `WpadWork.statuses` is at `+0x6C` with the newest sample
#: first, and `KPADStatus.buttonsHeld` is its first field (D67, D68).
_COMBO_BLOCK = """
/*
    Button combinations.

    The game reads its own controller every frame, so a mod can read the same
    state. NOTE: This is not what D48 ruled out -- that was about *injecting* input
    into Dolphin from outside, for unattended tests, and says nothing about the
    game's own input. Conflating the two closed off this feature for weeks.

    Layout, all from spm-headers and confirmed against a running game:
      wpadGetWork()            spm/wpadmgr.h, returns WpadWork *
      WpadWork.statuses        +0x6C, [controller][age], newest age is 0
      KPADStatus.buttonsHeld   +0x00, and KPADStatus is 0x84 bytes

    NOTE: Masks are tested with `(held & mask) == mask`, never `held == mask`.
    Bit 31 of `buttonsHeld` flips between frames while the controller is
    untouched -- measured in D67 -- so an equality test would match on roughly
    half the frames and read as flaky hardware.

    Edge-triggered: a combination fires once when it becomes held, not sixty
    times a second while it stays held.
*/

extern void *wpadGetWork(void);

#define BLECK_WPAD_STATUSES 0x6C
#define BLECK_COMBO_COUNT {count}

static const u32 bleck_combo_masks[BLECK_COMBO_COUNT] = {{
{masks}}};

static const s32 *const bleck_combo_scripts[BLECK_COMBO_COUNT] = {{
{scripts}}};

/*
    Which combinations were held last frame, one bit each.

    Starts all-ones for two reasons: it is non-zero, so it lands in .data rather
    than .bss whose zeroing the loader does not document -- and it means every
    combination counts as already-held until it has been seen released. A button
    held while the game boots therefore cannot fire anything.
*/
static u32 bleck_combo_down = 0xFFFFFFFFu;

static u32 bleck_buttons_held(void)
{{
    u8 *work = (u8 *) wpadGetWork();

    /* Null before wpadInit has run; reading through it would fault. */
    if (work == 0)
        return 0;
    return *(volatile u32 *) (work + BLECK_WPAD_STATUSES);
}}

static void bleck_combos_on_seq(u32 seq)
{{
    u32 held, i, bit;

    /* evtEntry needs the script VM, which needs gameplay. Watching earlier is
       tempting and is what hung the game in D65. */
    if (seq != BLECK_SEQ_GAME)
        return;

    held = bleck_buttons_held();
    for (i = 0; i < BLECK_COMBO_COUNT; i++)
    {{
        bit = 1u << i;
        if ((held & bleck_combo_masks[i]) == bleck_combo_masks[i])
        {{
            if ((bleck_combo_down & bit) == 0)
            {{
                bleck_combo_down |= bit;
                evtEntry(bleck_combo_scripts[i], 0, 0);
            }}
        }}
        else
        {{
            bleck_combo_down &= ~bit;
        }}
    }}
}}
"""

#: One trampoline per sequence, because the game passes no index of its own.
_SEQ_STUBS = """
static void bleck_seq0(void *w) { bleck_after_seq(0, w); }
static void bleck_seq1(void *w) { bleck_after_seq(1, w); }
static void bleck_seq2(void *w) { bleck_after_seq(2, w); }
static void bleck_seq3(void *w) { bleck_after_seq(3, w); }
static void bleck_seq4(void *w) { bleck_after_seq(4, w); }
static void bleck_seq5(void *w) { bleck_after_seq(5, w); }

static SeqFunc *const bleck_hooks[BLECK_SEQ_COUNT] = {
    bleck_seq0, bleck_seq1, bleck_seq2,
    bleck_seq3, bleck_seq4, bleck_seq5,
};
"""

#: Installs the sequence hooks, as the body of `_prolog`.
_SEQ_INSTALL = """    u32 i;

    for (i = 0; i < BLECK_SEQ_COUNT; i++)
    {
        bleck_real_main[i] = seq_data[i].main;
        seq_data[i].main = bleck_hooks[i];
    }

"""

#: For a mod with nothing to schedule and no map to watch.
_PLAIN_PROLOG = """
void _prolog(void)
{
    mod_prolog();
}
"""

_ENTRY_POINTS = """
void _epilog(void)
{
}

void _unresolved(void)
{
}
"""


@dataclass(frozen=True)
class Banner:
    """An on-screen label naming the mod that is loaded.

    A disc looks identical to a stock one until something visibly differs, so a
    player juggling several builds has no way to tell which is in the drive.
    This draws the answer on the screen.
    """

    text: str
    sequences: tuple[int, ...] = (1,)
    """Sequence indices to draw on. Defaults to the title screen."""

    @property
    def flags(self) -> str:
        """The `sequences` set rendered as a C initialiser, one flag per row."""
        on = set(self.sequences)
        return ", ".join(
            "1" if index in on else "0" for index in range(len(SEQUENCE_NAMES))
        )


@dataclass(frozen=True)
class MapHook:
    """A compiled script attached to one map's init script."""

    map_name: str
    script: str
    """Name of a script in the same program, not a C identifier."""


@dataclass(frozen=True)
class ComboHook:
    """A button combination that starts a script.

    The mask arrives already resolved: the manifest names a combination and
    `bleck.yml` says which buttons it is, so by the time the emitter sees it
    there is nothing left to look up. `name` is carried only so the generated C
    can say which combination a table row is.
    """

    name: str
    mask: int
    script: str

    @property
    def comment(self) -> str:
        return f"/* {self.name} */"


#: One bit per combination in `bleck_combo_down`, so this is a hard ceiling.
#: Shared with map hooks, which have the same shape of bitmask.
MAX_COMBOS = 32


@dataclass(frozen=True)
class Scaffolding:
    """Everything the generated module does besides run its entry script.

    Grouped rather than passed as four parallel arguments because they are one
    idea — what this module is wired up to do — and because they kept arriving
    together at every call site anyway. Each one adds a line to the same
    per-frame sequence hook.
    """

    map_hooks: list[MapHook] = field(default_factory=list)
    """Scripts started on arrival at a named map."""

    banner: Banner | None = None
    """The on-screen label naming the mod."""

    boot_script: str = ""
    """A script started once, on the first frame of gameplay."""

    combos: list[ComboHook] = field(default_factory=list)
    """Button combinations that start scripts."""

    require_entry: bool = True
    """Whether a script called `main` must exist.

    Off for `bleck script check`, where insisting on an entry point would be a
    rule about mods imposed on someone checking a file's syntax.
    """

    @property
    def needs_entry_script(self) -> bool:
        """A mod needs `main` only when nothing else can start a script.

        Map hooks, boot maps and button combinations each bring their own way
        in, so requiring `main` alongside any of them would be ceremony.
        """
        return (
            self.require_entry
            and not self.map_hooks
            and not self.boot_script
            and not self.combos
        )


@dataclass(frozen=True)
class GeneratedSource:
    """C source for a compiled program, plus what it needs from the linker."""

    text: str
    entry_script: str
    external_symbols: list[str]

    @property
    def line_count(self) -> int:
        return len(self.text.splitlines())


def _c_string(text: str) -> str:
    """Escape a Python string as a C string literal.

    Non-ASCII is escaped byte-wise from UTF-8 rather than emitted raw, so the
    generated file stays pure ASCII and cannot be re-encoded by an editor into
    something the compiler reads differently.
    """
    out = ""
    for byte in text.encode("utf-8"):
        char = chr(byte)
        if char == "\\":
            out += "\\\\"
        elif char == '"':
            out += '\\"'
        elif char == "\n":
            out += "\\n"
        elif char == "\t":
            out += "\\t"
        elif char == "\r":
            out += "\\r"
        elif 0x20 <= byte < 0x7F:
            out += char
        else:
            # Octal, not hex: a hex escape in C consumes every following hex
            # digit, so "\x41" followed by a literal 'B' would parse as one
            # oversized escape. Octal is capped at three digits.
            out += f"\\{byte:03o}"
    return f'"{out}"'


def _word_text(word: Word) -> str:
    if isinstance(word, Literal):
        return str(word.value)
    if isinstance(word, SymbolWord):
        return f"(s32) &{word.name}"
    if isinstance(word, StringWord):
        return f"(s32) {_PREFIX}string_{word.index}"
    if isinstance(word, ScriptWord):
        return f"(s32) {_PREFIX}script_{word.name}"
    raise TypeError(f"unknown word type {type(word).__name__}")


def _script_array(script: CompiledScript) -> str:
    lines = [
        f"/* {script.name}: {len(script.words)} words, "
        f"{script.slots_used} of 16 local slots used */",
        f"const s32 {_PREFIX}script_{script.name}[] = {{",
    ]
    # Four per line: enough to be compact, few enough that a diff points at a
    # small region when bytecode changes.
    row: list[str] = []
    for word in script.words:
        row.append(_word_text(word))
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def _map_block(hooks: list[MapHook]) -> str:
    """Map names, the scripts they start, and the sequence watcher."""
    prefix = f"{_PREFIX}map_"
    tables = "".join(
        _MAP_TABLE.format(prefix=prefix, index=index, name=_c_string(hook.map_name))
        for index, hook in enumerate(hooks)
    )
    return _MAP_BLOCK.format(
        count=len(hooks),
        tables=tables,
        name_list="".join(f"    {prefix}name_{i},\n" for i in range(len(hooks))),
        script_list="".join(f"    {_PREFIX}script_{h.script},\n" for h in hooks),
    )


def _banner_block(banner: Banner) -> str:
    return _BANNER_BLOCK.format(text=_c_string(banner.text), flags=banner.flags)


def _combo_block(hooks: list[ComboHook]) -> str:
    """Mask and script tables, plus the per-frame watcher."""
    if len(hooks) > MAX_COMBOS:
        raise ScriptError(
            f"{len(hooks)} button combinations declared, but at most "
            f"{MAX_COMBOS} are supported -- `bleck_combo_down` tracks one bit "
            f"each in a 32-bit word.",
            Position(),
        )
    return _COMBO_BLOCK.format(
        count=len(hooks),
        masks="".join(f"    0x{hook.mask:08X}u,  {hook.comment}\n" for hook in hooks),
        scripts="".join(f"    {_PREFIX}script_{hook.script},\n" for hook in hooks),
    )


def boot_source(map_name: str, delay: int = BOOT_DELAY_FRAMES) -> str:
    """The script text a `code.boot` declaration desugars into.

    Generated as *source* and run through the ordinary compiler rather than
    emitted as bytecode. That is the difference between a feature and a special
    case: the map name goes through the same string table, the call goes through
    the same symbol-table check that would reject `evt_seq_mapchange` if it were
    not linkable, and the result shows up in build output as a script like any
    other.

    `map_name` is validated against the game's own map list before it gets here,
    so it cannot carry anything that needs escaping.
    """
    return (
        f"-- Generated by bleck from `code.boot`: start the game at {map_name}.\n"
        "--\n"
        "-- Edit mod.json, not this. See docs/testing.md.\n"
        f"script {BOOT_SCRIPT} {{\n"
        f"    wait({delay})\n"
        "    -- Door 0 means 'use the map's own default entrance', which\n"
        "    -- spm/map_data.h documents as the behaviour for a null door name.\n"
        f'    evt_seq_mapchange("{map_name}", 0)\n'
        "}\n"
    )


def _footer(
    entry: str,
    hooks: list[MapHook],
    banner: Banner | None = None,
    boot: str = "",
    combos: list[ComboHook] | None = None,
) -> str:
    """Assemble the scaffolding that runs the mod, from the pieces it needs.

    A free-running script and a map hook want the same per-frame hook on the
    sequence table -- one to start and re-start itself, the other to notice
    where the game went. A mod using both installs one set of hooks, not two.
    """
    combos = list(combos or [])
    if not entry and not hooks and banner is None and not boot and not combos:
        return _PLAIN_PROLOG + _ENTRY_POINTS

    parts = [_SEQ_TABLE]
    body = ""

    if banner is not None:
        parts.append(_banner_block(banner))
        body += "    if (bleck_banner_on[seq])\n        bleck_draw_banner();\n"
    if hooks:
        parts.append(_map_block(hooks))
        body += "    bleck_maps_on_seq(seq);\n"
    if combos:
        parts.append(_combo_block(combos))
        body += "    bleck_combos_on_seq(seq);\n"
    if entry:
        parts.append(_SCRIPT_START % entry)
        body += "    bleck_start_entry(seq);\n"
    # Last, so anything else due this frame has already run: the boot script
    # tears the world down a couple of seconds later.
    if boot:
        parts.append(_BOOT_BLOCK.format(script=boot))
        body += "    bleck_boot_on_seq(seq);\n"

    parts.append(
        "\nstatic void bleck_after_seq(u32 seq, void *work)\n"
        "{\n"
        f"{body}"
        "\n    if (bleck_real_main[seq] != 0)\n"
        "        bleck_real_main[seq](work);\n"
        "}\n"
    )
    parts.append(_SEQ_STUBS)
    parts.append(f"\nvoid _prolog(void)\n{{\n{_SEQ_INSTALL}    mod_prolog();\n}}\n")
    parts.append(_ENTRY_POINTS)
    return "".join(parts)


def generate_bare(
    origin: str = "native sources", banner: Banner | None = None
) -> GeneratedSource:
    """Scaffolding for a mod that ships only native C.

    The REL format still needs its three entry points, and the mod still needs
    somewhere to be called from, but there is no script to schedule.
    """
    text = _HEADER.format(origin=origin) + "\n" + MOD_HOOK + _footer("", [], banner)
    _require_ascii(text)
    return GeneratedSource(text=text, entry_script="", external_symbols=[])


def generate(
    program: CompiledProgram,
    origin: str = "a script",
    scaffolding: Scaffolding | None = None,
) -> GeneratedSource:
    """Render a compiled program as a single C translation unit."""
    plan = scaffolding or Scaffolding()
    hooks = list(plan.map_hooks)
    _check_map_hooks(program, hooks)
    _check_combo_hooks(program, plan.combos)
    _check_boot_script(program, plan.boot_script)
    entry = _entry_script(program, required=plan.needs_entry_script)

    parts = [_HEADER.format(origin=origin)]

    if program.called_symbols:
        parts.append(
            "/* Game functions called by USER_FUNC, bound by elf2rel. */\n"
            + "\n".join(f"extern void {name}(void);" for name in program.called_symbols)
        )

    parts.append(
        "/* Started by the game's script scheduler. */\n"
        "extern void *evtEntry(const s32 *script, u32 priority, u8 flags);"
    )
    parts.append(MOD_HOOK)

    if program.strings:
        parts.append(
            "\n".join(
                f"static const char {_PREFIX}string_{index}[] = {_c_string(text)};"
                for index, text in enumerate(program.strings)
            )
        )

    if len(program.scripts) > 1:
        # Scripts may spawn each other in any order, so every array is declared
        # before any is defined.
        parts.append(
            "\n".join(
                f"extern const s32 {_PREFIX}script_{script.name}[];"
                for script in program.scripts
            )
        )

    parts.extend(_script_array(script) for script in program.scripts)
    parts.append(
        _footer(
            f"{_PREFIX}script_{entry}" if entry else "",
            hooks,
            plan.banner,
            boot=f"{_PREFIX}script_{plan.boot_script}" if plan.boot_script else "",
            combos=plan.combos,
        )
    )

    text = "\n\n".join(parts)
    _require_ascii(text)
    return GeneratedSource(
        text=text,
        entry_script=entry,
        external_symbols=list(program.called_symbols),
    )


def _require_ascii(text: str) -> None:
    """Guard the invariant that generated C is pure ASCII.

    Mods get built on Linux, macOS and Windows, whose compilers and editors do
    not agree on a default source encoding. String contents are already escaped
    byte-wise, so the only way a non-ASCII character reaches here is a comment
    template in this module -- which is a `bleck` bug, and better caught during
    generation than as a mojibake comment in someone else's build log.
    """
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        raise ValueError(
            f"generated C contains non-ASCII {offending!r}; "
            "this is a bug in bleck's code templates"
        ) from exc


def _check_combo_hooks(program: CompiledProgram, hooks: list[ComboHook]) -> None:
    """Every combination's script has to exist, and be spelled the same twice.

    Same failure as a map hook: `mod.json` names a script, the source declares
    one, and nothing connects them until here. Without this the C compiler
    reports an undefined `bleck_script_wrap_home`, which says nothing about the
    manifest line that asked for it.
    """
    names = [script.name for script in program.scripts]
    for hook in hooks:
        if hook.script in names:
            continue
        listed = ", ".join(names) or "none"
        suggestion = difflib.get_close_matches(hook.script, names, n=1, cutoff=0.6)
        hint = f"\n  Did you mean {suggestion[0]!r}?" if suggestion else ""
        raise ScriptError(
            f"mod.json binds combo {hook.name!r} to script {hook.script!r}, "
            f"but this file declares no such script "
            f"(it declares: {listed}).{hint}",
            Position(),
        )


def _check_map_hooks(program: CompiledProgram, hooks: list[MapHook]) -> None:
    """Every attached script has to exist, and be named the same way twice.

    The manifest names a script; the source declares one. Nothing links the two
    until here, so a typo would otherwise reach the C compiler as an undefined
    symbol -- a message about `bleck_script_on_arrve` that says nothing about
    `mod.json`.
    """
    names = [script.name for script in program.scripts]
    for hook in hooks:
        if hook.script in names:
            continue
        listed = ", ".join(names) or "none"
        suggestion = difflib.get_close_matches(hook.script, names, n=1, cutoff=0.6)
        hint = f"\n  Did you mean {suggestion[0]!r}?" if suggestion else ""
        raise ScriptError(
            f"mod.json attaches {hook.script!r} to map {hook.map_name!r}, "
            f"but this file declares no such script "
            f"(it declares: {listed}).{hint}",
            Position(),
        )


def _check_boot_script(program: CompiledProgram, name: str) -> None:
    """The boot script has to be in the program the caller compiled.

    `bleck` generates the source for it, so this failing means the generated
    text and the emitter disagree — a bug here rather than in anyone's mod. It
    is checked anyway because the alternative is an undefined C symbol, which
    surfaces as a linker error naming `bleck_script_bleck_boot` and nothing at
    all about the `--map` flag that asked for it.
    """
    if not name or any(script.name == name for script in program.scripts):
        return
    listed = ", ".join(script.name for script in program.scripts) or "none"
    raise ScriptError(
        f"boot script {name!r} is missing from the compiled program "
        f"(it declares: {listed}). This is a bug in bleck.",
        Position(),
    )


def _entry_script(program: CompiledProgram, required: bool = True) -> str:
    names = [script.name for script in program.scripts]
    if ENTRY_SCRIPT in names:
        return ENTRY_SCRIPT
    if not required:
        return ""
    listed = ", ".join(names)
    raise ScriptError(
        f"no script named {ENTRY_SCRIPT!r} to start "
        f"(this file declares: {listed}). "
        f"Rename one to {ENTRY_SCRIPT!r}, or spawn the others from it",
        Position(),
    )
