"""Writing compiled scripts out as C, for the existing REL toolchain to build.

Generating C rather than an object file directly is what lets this reuse the
whole proven path — devkitPPC, the relocatable link, `pyelf2rel` — instead of
becoming a second, parallel code generator that has to learn ELF and PowerPC
relocations by itself.

It also solves the address problem cleanly. Scripts refer to game functions by
name; the generated C declares them `extern` and takes their address, and
`elf2rel` binds each one through the symbol list at REL-build time. So no game
address is ever written by `bleck`, and no symbol list has to be redistributed
with it.
"""

from __future__ import annotations

import difflib
from dataclasses import dataclass

from bleck.script.compiler import (
    CompiledProgram,
    CompiledScript,
    Literal,
    ScriptWord,
    StringWord,
    SymbolWord,
    Word,
)
from bleck.script.errors import Position, ScriptError

#: The script the loader starts. Chosen by name rather than by position so that
#: reordering a file cannot silently change which script runs.
ENTRY_SCRIPT = "main"

_PREFIX = "bleck_"

_HEADER = """\
/*
    Generated by `bleck` from {origin}.
    Do not edit: rebuild the script instead.

    This is an evt script module. The arrays below are bytecode for Super Paper
    Mario's own script VM. `_prolog` hooks the game's sequence table; the entry
    script is handed to the scheduler when gameplay starts, and re-started after
    anything that resets evt state, such as a map change.

    Game functions are referenced by name and resolved by `elf2rel` against a
    symbol list, so no addresses appear here.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;
"""

#: Defined in every generated module, so a mod's own C can run at load time
#: without owning `_prolog` itself. Weak, so a mod that supplies its own
#: strong definition overrides this empty one at link time.
MOD_HOOK = """/*
    A mod's own C may define `mod_prolog` to run when the module loads.

    This is a weak *definition* rather than a declaration, and the difference
    matters: a weak declaration leaves an undefined symbol, and `elf2rel` tries
    to resolve every undefined symbol against the game's list. `mod_prolog` is
    not a game function, so a script-only mod failed to build with
    "Missing 1 required symbol(s): mod_prolog". Defining it here means there is
    nothing left undefined, and a mod that supplies its own strong definition
    overrides this one at link time.

    `_prolog` stays owned by the generated code because it has to install the
    sequence hooks first -- see the comment below for why that ordering matters.

    Anything touching live engine state belongs in a sequence hook, not here:
    at load time the game is barely up. docs/hook-points.md has the timings.
*/
__attribute__((weak)) void mod_prolog(void)
{
}
"""


#: Running a script when a named map is reached.
#:
#: ⛔ This does *not* patch `MapData.initScript`, which was the obvious design
#: and does not work: it deadlocks the map loader (D51). Instead the sequence
#: hook watches where the game says it is going, and starts the script once
#: gameplay resumes -- both mechanisms already verified in D43.
_MAP_BLOCK = """
/*
    Map hooks.

    The game announces where it is going: during a map change, `seqWork.p0`
    holds the destination map's name. So arriving somewhere is observable
    without touching the game's own data at all -- the sequence hook notes the
    name on the way in, and starts the script once gameplay resumes.

    RULED OUT: patching `MapData.initScript` to chain the map's own script.
    It deadlocks -- the load freezes partway and never completes, whether the
    original is spawned blocking or detached. Measured, not guessed; see D51.

    Both halves of what is used instead are already proven: `evtEntry` from
    `seq_data[SEQ_GAME].main` is exactly how every bleck script starts (D43),
    and reading `seqWork.p0` during a map change is how the destination was
    identified in the first place (D47).
*/

typedef struct
{{
    s32 seq;
    s32 stage;
    const char *p0;
    const char *p1;
}} SeqWork;

extern SeqWork seqWork;

#define BLECK_SEQ_MAPCHANGE 3
#define BLECK_MAP_COUNT {count}
{tables}
static const char *const bleck_map_names[BLECK_MAP_COUNT] = {{
{name_list}}};

static const s32 *const bleck_map_scripts[BLECK_MAP_COUNT] = {{
{script_list}}};

/*
    Which maps are waiting to start, one bit each. Set while the map change is
    still in flight and consumed when gameplay resumes, because that is the
    moment evt is alive again -- a script started during the change would be
    torn down with the rest of evt state.
*/
static u32 bleck_map_pending = 0;

/* By hand: the module links -nostdlib, so there is no strcmp to call. */
static u32 bleck_same_name(const char *a, const char *b)
{{
    u32 i;

    if (a == 0 || b == 0)
        return 0;
    for (i = 0; a[i] != 0; i++)
        if (a[i] != b[i])
            return 0;
    return b[i] == 0;
}}

static void bleck_maps_on_seq(u32 seq)
{{
    u32 i;

    if (seq == BLECK_SEQ_MAPCHANGE)
    {{
        for (i = 0; i < BLECK_MAP_COUNT; i++)
            if (bleck_same_name(seqWork.p0, bleck_map_names[i]))
                bleck_map_pending |= (1 << i);
        return;
    }}

    if (seq != BLECK_SEQ_GAME || bleck_map_pending == 0)
        return;

    for (i = 0; i < BLECK_MAP_COUNT; i++)
    {{
        if (bleck_map_pending & (1 << i))
        {{
            bleck_map_pending &= ~(1 << i);
            evtEntry(bleck_map_scripts[i], 0, 0);
        }}
    }}
}}
"""

#: One map's name. The script it starts is referenced by the table below.
_MAP_TABLE = """
static const char {prefix}name_{index}[] = {name};
"""

#: Typedefs and the saved originals. Needed by anything wanting a per-frame
#: hook -- a free-running script, a map watcher, or both.
_SEQ_TABLE = """
/*
    Hooking the game's sequence table.

    `_prolog` runs the instant the loader links this module, far too early to
    hand anything to the script scheduler: the evt manager is not initialised
    yet, so `evtEntry` there does nothing at all. Hooking
    `seq_data[SEQ_GAME].init` does not work either. Both were measured, not
    guessed -- D38 and D40.

    What does work is `seq_data[SEQ_GAME].main`, verified by reading the running
    game's memory from outside the emulator: the script is created and then runs
    once per frame (D43).
*/

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

/* Resolved by name from the symbol list, like everything else here. */
extern SeqDef seq_data[];

/* spm/seqdrv.h: LOGO 0, TITLE 1, GAME 2, MAPCHANGE 3, GAMEOVER 4, LOAD 5 */
#define BLECK_SEQ_COUNT 6
#define BLECK_SEQ_GAME 2

/*
    Deliberately initialised to non-zero values so these land in .data rather
    than .bss. The loader allocates this module's bss but nothing documents
    whether it zeroes it, and depending on that would be a silent hazard.
*/
static SeqFunc *bleck_real_main[BLECK_SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};
"""

#: Starting the entry script, and keeping it started.
_SCRIPT_START = """
/*
    A script does not survive a map change (D43). evt state is torn down and
    rebuilt, and a script started once simply stops. So rather than starting
    once, every sequence other than gameplay re-arms a flag and gameplay starts
    the script whenever it is armed. That covers map changes, game overs and
    loads without needing to know which of them resets evt.
*/

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{
    if (seq != BLECK_SEQ_GAME)
    {
        bleck_needs_start = 1;
        return;
    }
    if (bleck_needs_start)
    {
        bleck_needs_start = 0;
        evtEntry(%s, 0, 0);
    }
}
"""

#: One trampoline per sequence, because the game passes no index of its own.
_SEQ_STUBS = """
static void bleck_seq0(void *w) { bleck_after_seq(0, w); }
static void bleck_seq1(void *w) { bleck_after_seq(1, w); }
static void bleck_seq2(void *w) { bleck_after_seq(2, w); }
static void bleck_seq3(void *w) { bleck_after_seq(3, w); }
static void bleck_seq4(void *w) { bleck_after_seq(4, w); }
static void bleck_seq5(void *w) { bleck_after_seq(5, w); }

static SeqFunc *const bleck_hooks[BLECK_SEQ_COUNT] = {
    bleck_seq0, bleck_seq1, bleck_seq2,
    bleck_seq3, bleck_seq4, bleck_seq5,
};
"""

#: Installs the sequence hooks, as the body of `_prolog`.
_SEQ_INSTALL = """    u32 i;

    for (i = 0; i < BLECK_SEQ_COUNT; i++)
    {
        bleck_real_main[i] = seq_data[i].main;
        seq_data[i].main = bleck_hooks[i];
    }

"""

#: For a mod with nothing to schedule and no map to watch.
_PLAIN_PROLOG = """
void _prolog(void)
{
    mod_prolog();
}
"""

_ENTRY_POINTS = """
void _epilog(void)
{
}

void _unresolved(void)
{
}
"""


@dataclass(frozen=True)
class MapHook:
    """A compiled script attached to one map's init script."""

    map_name: str
    script: str
    """Name of a script in the same program, not a C identifier."""


@dataclass(frozen=True)
class GeneratedSource:
    """C source for a compiled program, plus what it needs from the linker."""

    text: str
    entry_script: str
    external_symbols: list[str]

    @property
    def line_count(self) -> int:
        return len(self.text.splitlines())


def _c_string(text: str) -> str:
    """Escape a Python string as a C string literal.

    Non-ASCII is escaped byte-wise from UTF-8 rather than emitted raw, so the
    generated file stays pure ASCII and cannot be re-encoded by an editor into
    something the compiler reads differently.
    """
    out = ""
    for byte in text.encode("utf-8"):
        char = chr(byte)
        if char == "\\":
            out += "\\\\"
        elif char == '"':
            out += '\\"'
        elif char == "\n":
            out += "\\n"
        elif char == "\t":
            out += "\\t"
        elif char == "\r":
            out += "\\r"
        elif 0x20 <= byte < 0x7F:
            out += char
        else:
            # Octal, not hex: a hex escape in C consumes every following hex
            # digit, so "\x41" followed by a literal 'B' would parse as one
            # oversized escape. Octal is capped at three digits.
            out += f"\\{byte:03o}"
    return f'"{out}"'


def _word_text(word: Word) -> str:
    if isinstance(word, Literal):
        return str(word.value)
    if isinstance(word, SymbolWord):
        return f"(s32) &{word.name}"
    if isinstance(word, StringWord):
        return f"(s32) {_PREFIX}string_{word.index}"
    if isinstance(word, ScriptWord):
        return f"(s32) {_PREFIX}script_{word.name}"
    raise TypeError(f"unknown word type {type(word).__name__}")


def _script_array(script: CompiledScript) -> str:
    lines = [
        f"/* {script.name}: {len(script.words)} words, "
        f"{script.slots_used} of 16 local slots used */",
        f"const s32 {_PREFIX}script_{script.name}[] = {{",
    ]
    # Four per line: enough to be compact, few enough that a diff points at a
    # small region when bytecode changes.
    row: list[str] = []
    for word in script.words:
        row.append(_word_text(word))
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def _map_block(hooks: list[MapHook]) -> str:
    """Map names, the scripts they start, and the sequence watcher."""
    prefix = f"{_PREFIX}map_"
    tables = "".join(
        _MAP_TABLE.format(prefix=prefix, index=index, name=_c_string(hook.map_name))
        for index, hook in enumerate(hooks)
    )
    return _MAP_BLOCK.format(
        count=len(hooks),
        tables=tables,
        name_list="".join(f"    {prefix}name_{i},\n" for i in range(len(hooks))),
        script_list="".join(f"    {_PREFIX}script_{h.script},\n" for h in hooks),
    )


def _footer(entry: str, hooks: list[MapHook]) -> str:
    """Assemble the scaffolding that runs the mod, from the pieces it needs.

    A free-running script and a map hook want the same per-frame hook on the
    sequence table -- one to start and re-start itself, the other to notice
    where the game went. A mod using both installs one set of hooks, not two.
    """
    if not entry and not hooks:
        return _PLAIN_PROLOG + _ENTRY_POINTS

    parts = [_SEQ_TABLE]
    body = ""

    if hooks:
        parts.append(_map_block(hooks))
        body += "    bleck_maps_on_seq(seq);\n"
    if entry:
        parts.append(_SCRIPT_START % entry)
        body += "    bleck_start_entry(seq);\n"

    parts.append(
        "\nstatic void bleck_after_seq(u32 seq, void *work)\n"
        "{\n"
        f"{body}"
        "\n    if (bleck_real_main[seq] != 0)\n"
        "        bleck_real_main[seq](work);\n"
        "}\n"
    )
    parts.append(_SEQ_STUBS)
    parts.append(f"\nvoid _prolog(void)\n{{\n{_SEQ_INSTALL}    mod_prolog();\n}}\n")
    parts.append(_ENTRY_POINTS)
    return "".join(parts)


def generate_bare(origin: str = "native sources") -> GeneratedSource:
    """Scaffolding for a mod that ships only native C.

    The REL format still needs its three entry points, and the mod still needs
    somewhere to be called from, but there is no script to schedule.
    """
    text = _HEADER.format(origin=origin) + "\n" + MOD_HOOK + _footer("", [])
    _require_ascii(text)
    return GeneratedSource(text=text, entry_script="", external_symbols=[])


def generate(
    program: CompiledProgram,
    origin: str = "a script",
    map_hooks: list[MapHook] | None = None,
    require_entry: bool = True,
) -> GeneratedSource:
    """Render a compiled program as a single C translation unit."""
    hooks = list(map_hooks or [])
    _check_map_hooks(program, hooks)
    # A mod that only attaches to maps has nothing to free-run, so `main` stops
    # being required the moment there is another way for a script to start.
    entry = _entry_script(program, required=require_entry and not hooks)

    parts = [_HEADER.format(origin=origin)]

    if program.called_symbols:
        parts.append(
            "/* Game functions called by USER_FUNC, bound by elf2rel. */\n"
            + "\n".join(f"extern void {name}(void);" for name in program.called_symbols)
        )

    parts.append(
        "/* Started by the game's script scheduler. */\n"
        "extern void *evtEntry(const s32 *script, u32 priority, u8 flags);"
    )
    parts.append(MOD_HOOK)

    if program.strings:
        parts.append(
            "\n".join(
                f"static const char {_PREFIX}string_{index}[] = {_c_string(text)};"
                for index, text in enumerate(program.strings)
            )
        )

    if len(program.scripts) > 1:
        # Scripts may spawn each other in any order, so every array is declared
        # before any is defined.
        parts.append(
            "\n".join(
                f"extern const s32 {_PREFIX}script_{script.name}[];"
                for script in program.scripts
            )
        )

    parts.extend(_script_array(script) for script in program.scripts)
    parts.append(_footer(f"{_PREFIX}script_{entry}" if entry else "", hooks))

    text = "\n\n".join(parts)
    _require_ascii(text)
    return GeneratedSource(
        text=text,
        entry_script=entry,
        external_symbols=list(program.called_symbols),
    )


def _require_ascii(text: str) -> None:
    """Guard the invariant that generated C is pure ASCII.

    Mods get built on Linux, macOS and Windows, whose compilers and editors do
    not agree on a default source encoding. String contents are already escaped
    byte-wise, so the only way a non-ASCII character reaches here is a comment
    template in this module -- which is a `bleck` bug, and better caught during
    generation than as a mojibake comment in someone else's build log.
    """
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        raise ValueError(
            f"generated C contains non-ASCII {offending!r}; "
            "this is a bug in bleck's code templates"
        ) from exc


def _check_map_hooks(program: CompiledProgram, hooks: list[MapHook]) -> None:
    """Every attached script has to exist, and be named the same way twice.

    The manifest names a script; the source declares one. Nothing links the two
    until here, so a typo would otherwise reach the C compiler as an undefined
    symbol -- a message about `bleck_script_on_arrve` that says nothing about
    `mod.json`.
    """
    names = [script.name for script in program.scripts]
    for hook in hooks:
        if hook.script in names:
            continue
        listed = ", ".join(names) or "none"
        suggestion = difflib.get_close_matches(hook.script, names, n=1, cutoff=0.6)
        hint = f"\n  Did you mean {suggestion[0]!r}?" if suggestion else ""
        raise ScriptError(
            f"mod.json attaches {hook.script!r} to map {hook.map_name!r}, "
            f"but this file declares no such script "
            f"(it declares: {listed}).{hint}",
            Position(),
        )


def _entry_script(program: CompiledProgram, required: bool = True) -> str:
    names = [script.name for script in program.scripts]
    if ENTRY_SCRIPT in names:
        return ENTRY_SCRIPT
    if not required:
        return ""
    listed = ", ".join(names)
    raise ScriptError(
        f"no script named {ENTRY_SCRIPT!r} to start "
        f"(this file declares: {listed}). "
        f"Rename one to {ENTRY_SCRIPT!r}, or spawn the others from it",
        Position(),
    )
