/*
    Does `code.hooks` install, and is the hook entered?

    D94 proved the mechanism by hand: `bleck_code_hook` over `npcDispMain`
    counted 62,480 entries across 90 s in `mac_01`. This proves the *declarative*
    path -- nothing here calls `bleck_code_hook`. The manifest says

        "hooks": [{"function": "npcDispMain", "call": "countNpcs",
                   "mode": "replace"}]

    and the generated runtime resolves the symbol, derives the guard word from
    the base disc's `main.dol`, and installs the branch at `_prolog`.

    ⚠️ REPLACEMENT. `npcDispMain` never runs while this mod is loaded, so NPCs
    are not drawn. That is what makes it a probe rather than a feature.

    ⛔ Not `effMain`: stubbing the effect driver wedges the game in
    SEQ_MAPCHANGE and it never reaches gameplay (D94).

    The negative control is a second build with the guard word corrupted. Since
    `npcDispMain` only ticks once a map is live, a non-zero count also says
    gameplay in mac_01 was reached -- so a zero is absence rather than
    truncation only when the frame counters say the game got there.

    Report block, big-endian u32:

      +0x00  magic 'FHOK'
      +0x04  bleck_hook_count
      +0x08  bleck_hook_status[0]   1 pending 2 installed 3 refused
                                    4 misaligned 5 out of range
      +0x0C  entries into countNpcs
      +0x10  first instruction of npcDispMain, read back after install
      +0x14  &countNpcs
      +0x18  SEQ_GAME frames
      +0x1C  map changes seen
      +0x20  SEQ_MAPCHANGE frames
      +0x24  sentinel, written on the first entry

    Run with:  scripts/ingame.py fn-hook-probe --map mac_01 --words 16
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x46484F4BU /* 'FHOK' */
#define SENTINEL 0xB1ECB1ECU
#define REPORT_WORDS 16

#define SEQ_COUNT 6
#define SEQ_GAME 2
#define SEQ_MAPCHANGE 3

/* Generated by bleck from `code.hooks`. See runtime_c.HOOK_BLOCK. */
extern u32 bleck_hook_status[];
extern const u32 bleck_hook_count;

/* Bound by elf2rel against the symbol list; no address appears here. */
extern void npcDispMain(void);

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define HOOK_COUNT (probe[1])
#define HOOK_STATUS (probe[2])
#define HITS (probe[3])
#define READ_BACK (probe[4])
#define HOOK_AT (probe[5])
#define GAME_FRAMES (probe[6])
#define MAP_CHANGES (probe[7])
#define CHANGE_FRAMES (probe[8])
#define SENTINEL_AT (probe[9])

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Replaces `npcDispMain` entirely. Counting is all it has to do. */
void countNpcs(void)
{
    HITS += 1;
    SENTINEL_AT = SENTINEL;
}

static u32 lastSeq = 0xFFFFFFFFU;

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;
    if (seq == SEQ_MAPCHANGE)
    {
        CHANGE_FRAMES += 1;
        if (lastSeq != SEQ_MAPCHANGE)
            MAP_CHANGES += 1;
    }
    lastSeq = seq;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

/*
    `mod_prolog` runs *after* the generated `bleck_install_hooks`, so the status
    read here is final -- the same ordering `bleck_patch_status[]` relies on.
*/
void mod_prolog(void)
{
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    HOOK_COUNT = bleck_hook_count;
    HOOK_STATUS = bleck_hook_status[0];
    HOOK_AT = (u32) countNpcs;
    READ_BACK = *(volatile u32 *) npcDispMain;

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
