/*
    Does the derived guard actually refuse?

    A guard that has only ever passed has not been tested. `mods/fn-hook-probe`
    is the positive; this is the negative, and it makes the guard fail without
    editing anything bleck generated.

    TWO HOOKS ON ONE FUNCTION. Both name `npcDispMain`, so both carry the same
    guard word derived from `main.dol`: 9421FE40, the function's `stwu`
    prologue. They install in manifest order, so:

      hook 0  sees 9421FE40, matches, writes `b countNpcs`
      hook 1  sees the branch hook 0 just wrote, does NOT match, writes nothing

    That is exactly the version-mismatch case the guard exists for -- the word
    at the address is not the word the build recorded -- reproduced on demand
    rather than argued about.

    WHAT THE READBACK SETTLES. The two hook functions are at different
    addresses, so the branch at `npcDispMain` says which of them won. If hook 1
    had written anything, the readback would point at `neverRuns` instead of
    `countNpcs`. "Refused" and "wrote something harmless" are therefore
    distinguishable, which is the whole reason both addresses are reported.

    Report block, big-endian u32:

      +0x00  magic 'FHGD'
      +0x04  bleck_hook_count            expect 2
      +0x08  bleck_hook_status[0]        expect 2, installed
      +0x0C  bleck_hook_status[1]        expect 3, refused
      +0x10  entries into countNpcs
      +0x14  entries into neverRuns      expect 0
      +0x18  first instruction of npcDispMain, read back
      +0x1C  &countNpcs
      +0x20  &neverRuns
      +0x24  SEQ_GAME frames
      +0x28  map changes seen
      +0x2C  SEQ_MAPCHANGE frames

    Run with:  scripts/ingame.py fn-hook-guard --map mac_01 --words 16
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;

#define PROBE 0x80005000
#define MAGIC 0x46484744U /* 'FHGD' */
#define REPORT_WORDS 16

#define SEQ_COUNT 6
#define SEQ_GAME 2
#define SEQ_MAPCHANGE 3

/* Generated by bleck from `code.hooks`. See runtime_c.HOOK_BLOCK. */
extern u32 bleck_hook_status[];
extern const u32 bleck_hook_count;

/* Bound by elf2rel against the symbol list; no address appears here. */
extern void npcDispMain(void);

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

#define HOOK_COUNT (probe[1])
#define STATUS_0 (probe[2])
#define STATUS_1 (probe[3])
#define HITS_0 (probe[4])
#define HITS_1 (probe[5])
#define READ_BACK (probe[6])
#define AT_0 (probe[7])
#define AT_1 (probe[8])
#define GAME_FRAMES (probe[9])
#define MAP_CHANGES (probe[10])
#define CHANGE_FRAMES (probe[11])

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

/* Hook 0. Wins, because it installs first. */
void countNpcs(void)
{
    HITS_0 += 1;
}

/* Hook 1. Must never be entered: its guard sees hook 0's branch. */
void neverRuns(void)
{
    HITS_1 += 1;
}

static u32 lastSeq = 0xFFFFFFFFU;

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        GAME_FRAMES += 1;
    if (seq == SEQ_MAPCHANGE)
    {
        CHANGE_FRAMES += 1;
        if (lastSeq != SEQ_MAPCHANGE)
            MAP_CHANGES += 1;
    }
    lastSeq = seq;

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

void mod_prolog(void)
{
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;

    HOOK_COUNT = bleck_hook_count;
    STATUS_0 = bleck_hook_status[0];
    STATUS_1 = bleck_hook_status[1];
    AT_0 = (u32) countNpcs;
    AT_1 = (u32) neverRuns;
    READ_BACK = *(volatile u32 *) npcDispMain;

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
