/*
    Does the self-healing detour work, and can it read a live argument?

    `code.hooks` replaces: the original never runs. This calls the original
    anyway, by restoring its first instruction, calling it through its symbol,
    and re-installing the branch afterwards -- `bleck_trace_open` /
    `bleck_trace_close` in the generated runtime.

    WHY mapDataPtr IS THE TARGET. Three properties, and each one rules out a
    different way of being fooled:

      * the game cannot load a map without it, so a broken detour breaks the
        game visibly rather than quietly reporting a plausible zero;
      * its argument is a `const char *` map name, so a *correct* capture is
        readable as text and a garbage one is not -- "plausible-looking" is not
        available to it;
      * it returns a pointer into `mapData`, so a sane result is checkable
        against the DOL's own data span.

    So a run where the attract demo reaches aa4_01 and ls4_12 as usual AND the
    captured bytes spell map names is evidence about the detour, not just about
    the hook installing.

    ⚠️ The captured strings are copied into the report block here, not printed
    as pointers: an address proves nothing, and D94's first stage-2 run is the
    standing reminder that a number can be read as a finding when it is not one.

    Report block, big-endian u32:

      +0x00 ( 0)  magic 'FTRC'
      +0x04 ( 1)  bleck_hook_count
      +0x08 ( 2)  bleck_hook_status[0]  1 pending 2 installed 3 refused
                                        4 misaligned 5 out of range
      +0x0C ( 3)  bleck_traces[0].magic, B1EC7ACE if the record is where we think
      +0x10 ( 4)  calls    -- entries into the handler
      +0x14 ( 5)  nested   -- entries made while the detour was already open
      +0x18 ( 6)  blind    -- entries where the detour could not be opened
      +0x1C ( 7)  depth    -- must be 0 at rest; non-zero means a lost frame
      +0x20 ( 8)  first call's argument 0 (const char *)
      +0x24 ( 9)  most recent call's argument 0
      +0x28 (10)  first call's result (MapData *)
      +0x2C (11)  most recent call's result
      +0x30 (12)  first call's name, bytes 0..3
      +0x34 (13)  first call's name, bytes 4..7
      +0x38 (14)  first call's name, bytes 8..11
      +0x3C (15)  most recent call's name, bytes 0..3
      +0x40 (16)  most recent call's name, bytes 4..7
      +0x44 (17)  most recent call's name, bytes 8..11
      +0x48 (18)  first instruction of mapDataPtr, read back per frame
      +0x4C (19)  &traceMapDataPtr
      +0x50 (20)  bleck_hook_original(0) -- the guard derived from main.dol
      +0x54 (21)  time-base ticks spent in open + close, summed over all calls
      +0x58 (22)  time-base ticks spent inside the real mapDataPtr, summed
      +0x5C (23)  SEQ_GAME frames
      +0x60 (24)  map changes seen
      +0x64 (25)  sentinel, written on the first entry

    Run with:  scripts/ingame.py fn-trace-probe --words 28 --seconds 120
    No --map: the attract demo's own aa4_01 -> ls4_12 is the health check.
    Target: eu0.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;

#define PROBE 0x80005000
#define MAGIC 0x46545243U /* 'FTRC' */
#define SENTINEL 0xB1ECB1ECU
#define REPORT_WORDS 26

#define SEQ_COUNT 6
#define SEQ_GAME 2
#define SEQ_MAPCHANGE 3

/* Which hook this mod traces. One hook, so index 0. */
#define TRACE 0

/* How many bytes of a captured string reach the report block. */
#define NAME_BYTES 12
#define NAME_WORDS 3

#define TRACE_ARGS 4

/* MEM1 and MEM2, so a pointer can be sanity-checked before it is followed. */
#define RAM_LOW 0x80000000U
#define RAM_HIGH 0x94000000U

/* Generated by bleck from `code.hooks`. See runtime_c.HOOK_BLOCK. */
extern u32 bleck_hook_status[];
extern const u32 bleck_hook_count;

/*
    The trace runtime. See runtime_c.TRACE_BLOCK -- this layout is repeated
    here rather than shared through a header, exactly as probes repeat SeqDef.
*/
typedef struct
{
    u32 magic;
    u32 calls;
    u32 nested;
    u32 blind;
    u32 depth;
    u32 first[TRACE_ARGS];
    u32 last[TRACE_ARGS];
    u32 firstResult;
    u32 lastResult;
} BleckTrace;

extern BleckTrace bleck_traces[];
extern void bleck_trace_args(u32 index, u32 a0, u32 a1, u32 a2, u32 a3);
extern u32 bleck_trace_open(u32 index);
extern void bleck_trace_close(u32 index);
extern void bleck_trace_result(u32 index, u32 value);
extern u32 bleck_hook_original(u32 index);

/* Bound by elf2rel against the symbol list; no address appears here. */
extern void *mapDataPtr(const char *mapName);

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

extern SeqDef seq_data[];

static volatile u32 *const probe = (volatile u32 *) PROBE;

/*
    The 750's time base, read directly. No OS symbol is needed and none is
    trusted: `mftb` is the counter the hardware increments.

    ⚠️ Under Dolphin this advances by the emulator's cycle accounting, which is
    not the Wii's, so the number below is a Dolphin measurement of a Dolphin
    cost. It bounds the shape of the answer, not the hardware answer.
*/
static u32 ticks(void)
{
    u32 value;

    __asm__ __volatile__("mftb %0" : "=r"(value));
    return value;
}

/* Both start at 1, and 1 is subtracted when reported: a non-zero initialiser
   is what keeps them in .data, whose contents the loader does define. */
static u32 patchTicks = 1;
static u32 bodyTicks = 1;

/*
    Replaces mapDataPtr, then calls it.

    The prototype matches the real one exactly. That is not politeness: the
    handler forwards its arguments to the original, so a mismatched prototype
    corrupts the call rather than merely mis-recording it.

    If `bleck_trace_open` returns 0 the original must NOT be called -- its first
    instruction is still the branch back here. That path returns null, which the
    game will not survive; it is unreachable while the hook is installed and
    guarded, and reaching it is meant to be loud.
*/
void *traceMapDataPtr(const char *mapName)
{
    void *result = 0;
    u32 t0, t1, t2, t3;

    bleck_trace_args(TRACE, (u32) mapName, 0, 0, 0);
    t0 = ticks();
    if (bleck_trace_open(TRACE))
    {
        t1 = ticks();
        result = mapDataPtr(mapName);
        t2 = ticks();
        bleck_trace_close(TRACE);
        t3 = ticks();
        patchTicks += (t1 - t0) + (t3 - t2);
        bodyTicks += (t2 - t1);
    }
    bleck_trace_result(TRACE, (u32) result);
    return result;
}

/* Bytes at `pointer` into three report words, zero-padded past the terminator. */
static void copyName(u32 at, u32 pointer)
{
    const u8 *text = (const u8 *) pointer;
    u32 word = 0;
    u32 i, byte;
    u32 done = 0;

    if (pointer < RAM_LOW || pointer >= RAM_HIGH || (pointer & 3) != 0)
    {
        for (i = 0; i < NAME_WORDS; i++)
            probe[at + i] = 0;
        return;
    }
    for (i = 0; i < NAME_BYTES; i++)
    {
        byte = done ? 0 : text[i];
        if (byte == 0)
            done = 1;
        word = (word << 8) | byte;
        if ((i & 3) == 3)
        {
            probe[at + (i >> 2)] = word;
            word = 0;
        }
    }
}

static u32 lastSeq = 0xFFFFFFFFU;

static void refreshReport(void)
{
    const BleckTrace *trace = &bleck_traces[TRACE];

    probe[3] = trace->magic;
    probe[4] = trace->calls;
    probe[5] = trace->nested;
    probe[6] = trace->blind;
    probe[7] = trace->depth;
    probe[8] = trace->first[0];
    probe[9] = trace->last[0];
    probe[10] = trace->firstResult;
    probe[11] = trace->lastResult;
    copyName(12, trace->first[0]);
    copyName(15, trace->last[0]);
    /* At rest this is the branch. Read every frame so a detour left open --
       which would show the original prologue here -- is visible. */
    probe[18] = *(volatile u32 *) mapDataPtr;
    probe[21] = patchTicks - 1;
    probe[22] = bodyTicks - 1;
    probe[25] = SENTINEL;
}

static SeqFunc *realMain[SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};

static void onSequenceFrame(u32 seq, void *work)
{
    if (seq == SEQ_GAME)
        probe[23] += 1;
    if (seq == SEQ_MAPCHANGE && lastSeq != SEQ_MAPCHANGE)
        probe[24] += 1;
    lastSeq = seq;
    refreshReport();

    if (realMain[seq] != 0)
        realMain[seq](work);
}

static void seq0(void *w) { onSequenceFrame(0, w); }
static void seq1(void *w) { onSequenceFrame(1, w); }
static void seq2(void *w) { onSequenceFrame(2, w); }
static void seq3(void *w) { onSequenceFrame(3, w); }
static void seq4(void *w) { onSequenceFrame(4, w); }
static void seq5(void *w) { onSequenceFrame(5, w); }

static SeqFunc *const hooks[SEQ_COUNT] = {seq0, seq1, seq2, seq3, seq4, seq5};

/*
    `mod_prolog` runs *after* the generated `bleck_install_hooks`, so the status
    read here is final -- the same ordering `bleck_patch_status[]` relies on.
*/
void mod_prolog(void)
{
    u32 i;

    for (i = 0; i < REPORT_WORDS; i++)
        probe[i] = 0;
    probe[0] = MAGIC;
    probe[1] = bleck_hook_count;
    probe[2] = bleck_hook_status[TRACE];
    probe[19] = (u32) traceMapDataPtr;
    probe[20] = bleck_hook_original(TRACE);

    for (i = 0; i < SEQ_COUNT; i++)
    {
        realMain[i] = seq_data[i].main;
        seq_data[i].main = hooks[i];
    }
}
