"""The back end: a compiled program to one C translation unit.

`scaffold` is what a module is wired up to *do*, as values; `runtime_c` is the
C that ships inside every mod; `generate` assembles them.
"""

from bleck.script.emit.generate import (
    BoundCombo,
    BoundHook,
    GeneratedSource,
    ModPart,
    boot_source,
    generate,
    generate_bare,
    generate_merged,
)
from bleck.script.emit.scaffold import (
    BOOT_DELAY_FRAMES,
    BOOT_SCRIPT,
    DEFAULT_BANNER_SEQUENCES,
    DOOR_SCRIPTS,
    ENTRY_SCRIPT,
    MAX_COMBOS,
    MAX_MAP_HOOKS,
    NPC_SCRIPTS,
    SEQUENCE_NAMES,
    SUPPORTED_SELECTORS,
    Banner,
    ComboHook,
    DoorScript,
    FunctionHook,
    HookMode,
    MapHook,
    NpcScript,
    PatchKind,
    Scaffolding,
    ScriptPatch,
    ScriptReplacement,
    Sequence,
    mod_slug,
    prefix_for,
)

__all__ = [
    "BOOT_DELAY_FRAMES",
    "BOOT_SCRIPT",
    "DEFAULT_BANNER_SEQUENCES",
    "DOOR_SCRIPTS",
    "ENTRY_SCRIPT",
    "MAX_COMBOS",
    "MAX_MAP_HOOKS",
    "NPC_SCRIPTS",
    "SEQUENCE_NAMES",
    "SUPPORTED_SELECTORS",
    "Banner",
    "BoundCombo",
    "BoundHook",
    "ComboHook",
    "DoorScript",
    "FunctionHook",
    "GeneratedSource",
    "HookMode",
    "MapHook",
    "ModPart",
    "NpcScript",
    "PatchKind",
    "Scaffolding",
    "ScriptPatch",
    "ScriptReplacement",
    "Sequence",
    "boot_source",
    "generate",
    "generate_bare",
    "generate_merged",
    "mod_slug",
    "prefix_for",
]
