"""One compiled program as one C translation unit, for the REL toolchain to build.

Game functions are declared `extern` and bound by `elf2rel` at REL-build time,
so `bleck` never writes a game address and ships no symbol list.

Three modules share the work, and the imports run one way:

| module | what it owns |
|---|---|
| `blocks` | one C block at a time — a table, a guard, a bound identifier |
| `checks` | what must be true before any of it is written |
| here | the shared runtime footer, and the single-program entry points |
| `merge` | the same footer over several mods' programs at once |

`merge` reads this module for `Runtime` and `footer`; nothing reads `merge`
back.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from bleck.script.compiler.ir import CompiledProgram
from bleck.script.emit import blocks, checks, runtime_c, runtime_replace
from bleck.script.emit.blocks import BoundCombo, BoundHook
from bleck.script.emit.scaffold import (
    _PREFIX,
    BOOT_DELAY_FRAMES,
    BOOT_SCRIPT,
    Banner,
    FunctionHook,
    Scaffolding,
    ScriptPatch,
    ScriptReplacement,
)


@dataclass(frozen=True)
class GeneratedSource:
    """C source for a compiled program, plus what it needs from the linker."""

    text: str
    entry_script: str
    external_symbols: list[str]

    @property
    def line_count(self) -> int:
        return len(self.text.splitlines())


def boot_source(map_name: str, delay: int = BOOT_DELAY_FRAMES) -> str:
    """The script text a `code.boot` declaration desugars into.

    Emitted as source and run through the ordinary compiler, so it gets the same
    string table and symbol-table checks as any other script. `map_name` is
    validated against the game's map list upstream, so it needs no escaping.
    """
    return (
        f"-- Generated by bleck from `code.boot`: start the game at {map_name}.\n"
        "--\n"
        "-- Edit mod.json, not this. See docs/testing.md.\n"
        f"script {BOOT_SCRIPT} {{\n"
        f"    wait({delay})\n"
        "    -- Door 0 means 'use the map's own default entrance', which\n"
        "    -- spm/map_data.h documents as the behaviour for a null door name.\n"
        f'    evt_seq_mapchange("{map_name}", 0)\n'
        "}\n"
    )


@dataclass(frozen=True)
class Runtime:
    """The shared runtime block's contents, resolved to C identifiers.

    One value rather than a handful of arguments, because all three `generate*`
    entry points fill in the same set.
    """

    banner: Banner | None = None
    boot: str = ""
    """The boot script's C identifier, if the module has one."""

    combos: list[BoundCombo] = field(default_factory=list)
    namespace: str = _PREFIX
    run_cxx_ctors: bool = False
    """Whether `_prolog` walks `.ctors`. See `runtime_c.CTOR_BLOCK`."""

    patches: list[ScriptPatch] = field(default_factory=list)
    """In-place edits to the game's own scripts, applied from `_prolog`."""

    function_hooks: list[FunctionHook] = field(default_factory=list)
    """Game functions branch-replaced by the mod's own, from `_prolog`."""

    replacements: list[ScriptReplacement] = field(default_factory=list)
    """Vanilla scripts repointed at the mod's own, whole, from `_prolog`."""


def footer(entries: list[str], hooks: list[BoundHook], runtime: Runtime) -> str:
    """Assemble the shared runtime, from the pieces the module needs.

    Emitted **once** however many mods contributed: a second `_prolog` would be
    a second set of installs fighting over `seq_data`. Everything that needs a
    per-frame hook shares the one set installed here.
    """
    banner, boot, combos = runtime.banner, runtime.boot, list(runtime.combos)
    patches = list(runtime.patches)
    functions = list(runtime.function_hooks)
    replacements = list(runtime.replacements)
    patch_kinds = {patch.kind for patch in patches}
    apply_replacements = runtime_replace.REPLACE_APPLY if replacements else ""
    # Before `mod_prolog`, so a mod's own C can read `bleck_patch_status[]`.
    apply_patches = "    bleck_apply_patches();\n" if patches else ""
    install_hooks = "    bleck_install_hooks();\n" if functions else ""
    run_ctors = "    bleck_run_ctors();\n" if runtime.run_cxx_ctors else ""

    if not entries and not hooks and banner is None and not boot and not combos:
        if (
            not runtime.run_cxx_ctors
            and not patches
            and not functions
            and not replacements
        ):
            return runtime_c.PLAIN_PROLOG + runtime_c.ENTRY_POINTS
        head = runtime_c.CTOR_BLOCK if runtime.run_cxx_ctors else ""
        head += blocks.patch_block(patches) if patches else ""
        head += blocks.replace_block(replacements, patch_kinds) if replacements else ""
        head += blocks.hook_block(functions) if functions else ""
        return (
            head + f"\nvoid _prolog(void)\n{{\n{run_ctors}{apply_patches}"
            f"{apply_replacements}{install_hooks}    mod_prolog();\n}}\n"
            + runtime_c.ENTRY_POINTS
        )

    parts = [runtime_c.SEQ_TABLE]
    body = ""
    if runtime.run_cxx_ctors:
        parts.append(runtime_c.CTOR_BLOCK)
    if patches:
        parts.append(blocks.patch_block(patches))
    if replacements:
        parts.append(blocks.replace_block(replacements, patch_kinds))
    if functions:
        parts.append(blocks.hook_block(functions))

    if banner is not None:
        parts.append(blocks.banner_block(banner))
        body += "    if (bleck_banner_on[seq])\n        bleck_draw_banner();\n"
    if hooks:
        parts.append(blocks.map_block(hooks, runtime.namespace))
        body += "    bleck_maps_on_seq(seq);\n"
    if combos:
        parts.append(blocks.combo_block(combos))
        body += "    bleck_combos_on_seq(seq);\n"
    if len(entries) == 1:
        # The single-mod form.
        parts.append(runtime_c.SCRIPT_START % entries[0])
        body += "    bleck_start_entry(seq);\n"
    elif entries:
        parts.append(
            runtime_c.SCRIPT_START_MANY.format(
                count=len(entries),
                entries="".join(f"    {name},\n" for name in entries),
            )
        )
        body += "    bleck_start_entry(seq);\n"
    # Last: the boot script tears the world down a couple of seconds later, so
    # everything else due this frame must have run first.
    if boot:
        parts.append(runtime_c.BOOT_BLOCK.format(script=boot))
        body += "    bleck_boot_on_seq(seq);\n"

    parts.append(
        "\nstatic void bleck_after_seq(u32 seq, void *work)\n"
        "{\n"
        f"{body}"
        "\n    if (bleck_real_main[seq] != 0)\n"
        "        bleck_real_main[seq](work);\n"
        "}\n"
    )
    parts.append(runtime_c.SEQ_STUBS)
    # Constructors run before `mod_prolog`, as statics do before `main`.
    parts.append(
        f"\nvoid _prolog(void)\n{{\n{runtime_c.SEQ_INSTALL}"
        f"{run_ctors}{apply_patches}{apply_replacements}{install_hooks}"
        f"    mod_prolog();\n}}\n"
    )
    parts.append(runtime_c.ENTRY_POINTS)
    return "".join(parts)


#: The two lines every module opens with once the game's own symbols are
#: declared. ⚠️ `evtEntry` is declared even by a module with no script: the
#: shared runtime references it, and a missing declaration is a C error rather
#: than a link one.
EVT_ENTRY_DECL = (
    "/* Started by the game's script scheduler. */\n"
    "extern void *evtEntry(const s32 *script, u32 priority, u8 flags);"
)

EXTERNS_COMMENT = "/* Game functions called by USER_FUNC, bound by elf2rel. */\n"


def generate_bare(
    origin: str = "native sources",
    *,
    banner: Banner | None = None,
    run_cxx_ctors: bool = False,
    patches: list[ScriptPatch] | None = None,
    replacements: list[ScriptReplacement] | None = None,
    function_hooks: list[FunctionHook] | None = None,
) -> GeneratedSource:
    """Scaffolding for a mod that ships only native sources.

    The REL format still needs its three entry points; there is just no script
    to schedule.
    """
    text = (
        runtime_c.HEADER.format(origin=origin)
        + "\n"
        + runtime_c.MOD_HOOK
        + "\n"
        + runtime_c.CODE_PATCH
        + footer(
            [],
            [],
            Runtime(
                banner=banner,
                run_cxx_ctors=run_cxx_ctors,
                patches=list(patches or []),
                replacements=blocks.bind_replacements(list(replacements or []), _PREFIX),
                function_hooks=list(function_hooks or []),
            ),
        )
    )
    checks.require_ascii(text)
    return GeneratedSource(text=text, entry_script="", external_symbols=[])


def generate(
    program: CompiledProgram,
    origin: str = "a script",
    scaffolding: Scaffolding | None = None,
) -> GeneratedSource:
    """Render a compiled program as a single C translation unit."""
    plan = scaffolding or Scaffolding()
    hooks = list(plan.map_hooks)
    checks.check_map_hooks(program, hooks)
    checks.check_combo_hooks(program, plan.combos)
    checks.check_replacements(program, plan.replacements)
    checks.check_boot_script(program, plan.boot_script)
    entry = checks.entry_script(program, required=plan.needs_entry_script)

    parts = [runtime_c.HEADER.format(origin=origin)]

    if program.called_symbols:
        parts.append(
            EXTERNS_COMMENT
            + "\n".join(f"extern void {name}(void);" for name in program.called_symbols)
        )

    parts.append(EVT_ENTRY_DECL)
    parts.append(runtime_c.MOD_HOOK)
    parts.append(runtime_c.CODE_PATCH)

    parts.extend(blocks.program_section(program, plan.prefix))
    parts.append(
        footer(
            [f"{plan.prefix}script_{entry}"] if entry else [],
            blocks.bind_maps(hooks, plan.prefix),
            Runtime(
                banner=plan.banner,
                boot=(
                    f"{plan.prefix}script_{plan.boot_script}" if plan.boot_script else ""
                ),
                combos=blocks.bind_combos(plan.combos, plan.prefix),
                namespace=plan.prefix,
                run_cxx_ctors=plan.run_cxx_ctors,
                patches=list(plan.patches),
                replacements=blocks.bind_replacements(plan.replacements, plan.prefix),
                function_hooks=list(plan.function_hooks),
            ),
        )
    )

    text = "\n\n".join(parts)
    checks.require_ascii(text)
    return GeneratedSource(
        text=text,
        entry_script=entry,
        external_symbols=list(program.called_symbols),
    )
