"""The C that `bleck` generates into every mod: the bleck runtime.

Separated from `emit.py` because it is *data*, not logic — nearly five hundred
lines of C source that happens to live in Python strings. Keeping it here means
`emit.py` reads as what it is, an assembler of these pieces, and means a change
to the generated runtime shows up in a diff of one file whose whole purpose is
the runtime.

Every template is a `str.format` pattern, so literal braces are doubled. The
generated output must be pure ASCII: `emit._require_ascii` fails the build
otherwise, and it has caught a stray unicode character in a comment here twice.
"""

from __future__ import annotations

HEADER = """\
/*
    Generated by `bleck` from {origin}.
    Do not edit: rebuild the script instead.

    This is an evt script module. The arrays below are bytecode for Super Paper
    Mario's own script VM. `_prolog` hooks the game's sequence table; the entry
    script is handed to the scheduler when gameplay starts, and re-started after
    anything that resets evt state, such as a map change.

    Game functions are referenced by name and resolved by `elf2rel` against a
    symbol list, so no addresses appear here.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;
"""

#: Defined in every generated module, so a mod's own C can run at load time
#: without owning `_prolog` itself. Weak, so a mod that supplies its own
#: strong definition overrides this empty one at link time.
MOD_HOOK = """/*
    A mod's own C may define `mod_prolog` to run when the module loads.

    This is a weak *definition* rather than a declaration, and the difference
    matters: a weak declaration leaves an undefined symbol, and `elf2rel` tries
    to resolve every undefined symbol against the game's list. `mod_prolog` is
    not a game function, so a script-only mod failed to build with
    "Missing 1 required symbol(s): mod_prolog". Defining it here means there is
    nothing left undefined, and a mod that supplies its own strong definition
    overrides this one at link time.

    `_prolog` stays owned by the generated code because it has to install the
    sequence hooks first -- see the comment below for why that ordering matters.

    Anything touching live engine state belongs in a sequence hook, not here:
    at load time the game is barely up. docs/hook-points.md has the timings.
*/
__attribute__((weak)) void mod_prolog(void)
{
}
"""


#: Running a script when a named map is reached.
#:
#: ⛔ This does *not* patch `MapData.initScript`, which was the obvious design
#: and does not work: it deadlocks the map loader (D51). Instead the sequence
#: hook watches where the game says it is going, and starts the script once
#: gameplay resumes -- both mechanisms already verified in D43.
MAP_BLOCK = """
/*
    Map hooks.

    The game announces where it is going: during a map change, `seqWork.p0`
    holds the destination map's name. So arriving somewhere is observable
    without touching the game's own data at all -- the sequence hook notes the
    name on the way in, and starts the script once gameplay resumes.

    RULED OUT: patching `MapData.initScript` to chain the map's own script.
    It deadlocks -- the load freezes partway and never completes, whether the
    original is spawned blocking or detached. Measured, not guessed; see D51.

    Both halves of what is used instead are already proven: `evtEntry` from
    `seq_data[SEQ_GAME].main` is exactly how every bleck script starts (D43),
    and reading `seqWork.p0` during a map change is how the destination was
    identified in the first place (D47).
*/

typedef struct
{{
    s32 seq;
    s32 stage;
    const char *p0;
    const char *p1;
}} SeqWork;

extern SeqWork seqWork;

#define BLECK_SEQ_MAPCHANGE 3
#define BLECK_MAP_COUNT {count}
{tables}
static const char *const bleck_map_names[BLECK_MAP_COUNT] = {{
{name_list}}};

static const s32 *const bleck_map_scripts[BLECK_MAP_COUNT] = {{
{script_list}}};

/*
    Which maps are waiting to start, one bit each. Set while the map change is
    still in flight and consumed when gameplay resumes, because that is the
    moment evt is alive again -- a script started during the change would be
    torn down with the rest of evt state.
*/
static u32 bleck_map_pending = 0;

/* By hand: the module links -nostdlib, so there is no strcmp to call. */
static u32 bleck_same_name(const char *a, const char *b)
{{
    u32 i;

    if (a == 0 || b == 0)
        return 0;
    for (i = 0; a[i] != 0; i++)
        if (a[i] != b[i])
            return 0;
    return b[i] == 0;
}}

static void bleck_maps_on_seq(u32 seq)
{{
    u32 i;

    if (seq == BLECK_SEQ_MAPCHANGE)
    {{
        for (i = 0; i < BLECK_MAP_COUNT; i++)
            if (bleck_same_name(seqWork.p0, bleck_map_names[i]))
                bleck_map_pending |= (1 << i);
        return;
    }}

    if (seq != BLECK_SEQ_GAME || bleck_map_pending == 0)
        return;

    for (i = 0; i < BLECK_MAP_COUNT; i++)
    {{
        if (bleck_map_pending & (1 << i))
        {{
            bleck_map_pending &= ~(1 << i);
            evtEntry(bleck_map_scripts[i], 0, 0);
        }}
    }}
}}
"""

#: One map's name. The script it starts is referenced by the table below.
MAP_TABLE = """
static const char {prefix}name_{index}[] = {name};
"""

#: The on-screen label naming the loaded mod.
#:
#: Every call mirrors `spm-rel-loader`'s title-screen example, which is the only
#: known-working use of this API: start, style, measure, draw -- and draw
#: *before* delegating to the real sequence main.
BANNER_BLOCK = """
/*
    Naming the loaded mod on screen.

    Text is drawn in screen space, which is centred with y increasing upward:
    `spm-rel-loader` centres a string with `x = -(width / 2)` and places it near
    the top of the title screen with `y = 200`. So the visible area is roughly
    x -320..320 and y -240..240, and the bottom-right corner is (+320, -240).
    The margins below back off from that corner far enough to survive overscan.

    `FontGetMessageWidth` measures the string so it can be right-aligned rather
    than positioned by guesswork, which also keeps a long mod name on screen.
*/

extern void FontDrawStart(void);
extern void FontDrawEdge(void);
extern void FontDrawColor(u8 *color);
extern void FontDrawScale(float scale);
extern void FontDrawNoiseOff(void);
extern void FontDrawRainbowColorOff(void);
extern void FontDrawString(float x, float y, const char *text);
extern unsigned short FontGetMessageWidth(const char *text);

#define BLECK_BANNER_RIGHT 296.0f
#define BLECK_BANNER_BOTTOM (-200.0f)
#define BLECK_BANNER_SCALE 0.6f

static const char bleck_banner_text[] = {text};

/* wii/gx.h GXColor, four bytes. Not const: FontDrawColor overwrites alpha. */
static u8 bleck_banner_color[4] = {{255, 255, 255, 255}};

/* Which sequences draw it. .rodata, so the loader's bss handling is moot. */
static const u8 bleck_banner_on[BLECK_SEQ_COUNT] = {{{flags}}};

static void bleck_draw_banner(void)
{{
    float width;

    FontDrawStart();
    FontDrawEdge();
    FontDrawColor(bleck_banner_color);
    FontDrawScale(BLECK_BANNER_SCALE);
    FontDrawNoiseOff();
    FontDrawRainbowColorOff();

    width = (float) FontGetMessageWidth(bleck_banner_text) * BLECK_BANNER_SCALE;
    FontDrawString(BLECK_BANNER_RIGHT - width, BLECK_BANNER_BOTTOM,
                   bleck_banner_text);
}}
"""

#: Typedefs and the saved originals. Needed by anything wanting a per-frame
#: hook -- a free-running script, a map watcher, or both.
SEQ_TABLE = """
/*
    Hooking the game's sequence table.

    `_prolog` runs the instant the loader links this module, far too early to
    hand anything to the script scheduler: the evt manager is not initialised
    yet, so `evtEntry` there does nothing at all. Hooking
    `seq_data[SEQ_GAME].init` does not work either. Both were measured, not
    guessed -- D38 and D40.

    What does work is `seq_data[SEQ_GAME].main`, verified by reading the running
    game's memory from outside the emulator: the script is created and then runs
    once per frame (D43).
*/

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

/* Resolved by name from the symbol list, like everything else here. */
extern SeqDef seq_data[];

/* spm/seqdrv.h: LOGO 0, TITLE 1, GAME 2, MAPCHANGE 3, GAMEOVER 4, LOAD 5 */
#define BLECK_SEQ_COUNT 6
#define BLECK_SEQ_GAME 2

/*
    Deliberately initialised to non-zero values so these land in .data rather
    than .bss. The loader allocates this module's bss but nothing documents
    whether it zeroes it, and depending on that would be a silent hazard.
*/
static SeqFunc *bleck_real_main[BLECK_SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};
"""

#: Starting the entry script, and keeping it started.
SCRIPT_START = """
/*
    A script does not survive a map change (D43). evt state is torn down and
    rebuilt, and a script started once simply stops. So rather than starting
    once, every sequence other than gameplay re-arms a flag and gameplay starts
    the script whenever it is armed. That covers map changes, game overs and
    loads without needing to know which of them resets evt.
*/

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{
    if (seq != BLECK_SEQ_GAME)
    {
        bleck_needs_start = 1;
        return;
    }
    if (bleck_needs_start)
    {
        bleck_needs_start = 0;
        evtEntry(%s, 0, 0);
    }
}
"""

#: Booting straight into a chosen map.
#:
#: Deliberately *not* a re-armed hook like `_SCRIPT_START`: this fires once, on
#: the first frame of gameplay, and never again. Re-arming it would send the
#: game back to the same map every time it left, which is a loop rather than a
#: starting point.
BOOT_BLOCK = """
/*
    Booting into a map.

    An unattended boot reaches exactly two maps -- aa4_01 then ls4_12, the
    attract demo -- and controller input cannot be injected (D48), so every
    other map used to need a human. This starts a script on the first frame of
    gameplay that asks the game to go somewhere else instead (D52).

    Note what this does *not* do: it does not try to redirect the first map
    load, which would be faster. The game is asked to change maps through its
    own `evt_seq_mapchange`, exactly as a door would, so arriving here is the
    same arrival the game performs everywhere else. Overwriting `seqWork.p0`
    before the loader reads it is the obvious shortcut and is untested; D51 is
    what happens when the map loader is handed something it did not expect.

    `bleck_boot_pending` starts at 1 rather than 0 so it lands in .data. The
    loader allocates this module's bss but nothing documents whether it zeroes
    it, and a boot map that fired only on some builds would be a miserable bug.
*/

static u32 bleck_boot_pending = 1;

static void bleck_boot_on_seq(u32 seq)
{{
    if (seq != BLECK_SEQ_GAME || bleck_boot_pending == 0)
        return;
    bleck_boot_pending = 0;
    evtEntry({script}, 0, 0);
}}
"""

#: Starting a script when a button combination is pressed.
#:
#: The reading path is measured, not assumed: `wpadGetWork()` is at `0x8023697c`
#: in the eu0 lst, `WpadWork.statuses` is at `+0x6C` with the newest sample
#: first, and `KPADStatus.buttonsHeld` is its first field (D67, D68).
COMBO_BLOCK = """
/*
    Button combinations.

    The game reads its own controller every frame, so a mod can read the same
    state. NOTE: This is not what D48 ruled out -- that was about *injecting* input
    into Dolphin from outside, for unattended tests, and says nothing about the
    game's own input. Conflating the two closed off this feature for weeks.

    Layout, all from spm-headers and confirmed against a running game:
      wpadGetWork()            spm/wpadmgr.h, returns WpadWork *
      WpadWork.statuses        +0x6C, [controller][age], newest age is 0
      KPADStatus.buttonsHeld   +0x00, and KPADStatus is 0x84 bytes

    NOTE: Masks are tested with `(held & mask) == mask`, never `held == mask`.
    Bit 31 of `buttonsHeld` flips between frames while the controller is
    untouched -- measured in D67 -- so an equality test would match on roughly
    half the frames and read as flaky hardware.

    Edge-triggered: a combination fires once when it becomes held, not sixty
    times a second while it stays held.
*/

extern void *wpadGetWork(void);

#define BLECK_WPAD_STATUSES 0x6C
#define BLECK_COMBO_COUNT {count}

static const u32 bleck_combo_masks[BLECK_COMBO_COUNT] = {{
{masks}}};

static const s32 *const bleck_combo_scripts[BLECK_COMBO_COUNT] = {{
{scripts}}};

/*
    Which combinations were held last frame, one bit each.

    Starts all-ones for two reasons: it is non-zero, so it lands in .data rather
    than .bss whose zeroing the loader does not document -- and it means every
    combination counts as already-held until it has been seen released. A button
    held while the game boots therefore cannot fire anything.
*/
static u32 bleck_combo_down = 0xFFFFFFFFu;

static u32 bleck_buttons_held(void)
{{
    u8 *work = (u8 *) wpadGetWork();

    /* Null before wpadInit has run; reading through it would fault. */
    if (work == 0)
        return 0;
    return *(volatile u32 *) (work + BLECK_WPAD_STATUSES);
}}

static void bleck_combos_on_seq(u32 seq)
{{
    u32 held, i, bit;

    /* evtEntry needs the script VM, which needs gameplay. Watching earlier is
       tempting and is what hung the game in D65. */
    if (seq != BLECK_SEQ_GAME)
        return;

    held = bleck_buttons_held();
    for (i = 0; i < BLECK_COMBO_COUNT; i++)
    {{
        bit = 1u << i;
        if ((held & bleck_combo_masks[i]) == bleck_combo_masks[i])
        {{
            if ((bleck_combo_down & bit) == 0)
            {{
                bleck_combo_down |= bit;
                evtEntry(bleck_combo_scripts[i], 0, 0);
            }}
        }}
        else
        {{
            bleck_combo_down &= ~bit;
        }}
    }}
}}
"""

#: Starting several mods' entry scripts, when a disc merges more than one.
#:
#: The single-mod form above is kept rather than replaced, so a disc holding one
#: mod emits exactly what it always has. A loop over one element would behave
#: identically and produce a different file, and "the output changed but only
#: cosmetically" is a claim nobody can check cheaply.
SCRIPT_START_MANY = """
/*
    Entry scripts, one per mod sharing this module.

    Each mod's `main` is started, and all of them are re-armed together: they
    are all torn down by the same map change, so there is nothing to track
    separately (D43).
*/

#define BLECK_ENTRY_COUNT {count}

static const s32 *const bleck_entries[BLECK_ENTRY_COUNT] = {{
{entries}}};

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{{
    u32 i;

    if (seq != BLECK_SEQ_GAME)
    {{
        bleck_needs_start = 1;
        return;
    }}
    if (bleck_needs_start)
    {{
        bleck_needs_start = 0;
        for (i = 0; i < BLECK_ENTRY_COUNT; i++)
            evtEntry(bleck_entries[i], 0, 0);
    }}
}}
"""

#: A banner above each mod's own section of the merged module.
MOD_SECTION = """
/* ------------------------------------------------------------------------
   {name}
   ------------------------------------------------------------------------ */
"""

#: One trampoline per sequence, because the game passes no index of its own.
SEQ_STUBS = """
static void bleck_seq0(void *w) { bleck_after_seq(0, w); }
static void bleck_seq1(void *w) { bleck_after_seq(1, w); }
static void bleck_seq2(void *w) { bleck_after_seq(2, w); }
static void bleck_seq3(void *w) { bleck_after_seq(3, w); }
static void bleck_seq4(void *w) { bleck_after_seq(4, w); }
static void bleck_seq5(void *w) { bleck_after_seq(5, w); }

static SeqFunc *const bleck_hooks[BLECK_SEQ_COUNT] = {
    bleck_seq0, bleck_seq1, bleck_seq2,
    bleck_seq3, bleck_seq4, bleck_seq5,
};
"""

#: Installs the sequence hooks, as the body of `_prolog`.
SEQ_INSTALL = """    u32 i;

    for (i = 0; i < BLECK_SEQ_COUNT; i++)
    {
        bleck_real_main[i] = seq_data[i].main;
        seq_data[i].main = bleck_hooks[i];
    }

"""

#: For a mod with nothing to schedule and no map to watch.
PLAIN_PROLOG = """
void _prolog(void)
{
    mod_prolog();
}
"""

ENTRY_POINTS = """
void _epilog(void)
{
}

void _unresolved(void)
{
}
"""
