"""The C that `bleck` generates into every mod: the bleck runtime.

Every template is a `str.format` pattern, so literal braces are doubled, and
the generated output must be pure ASCII — `generate._require_ascii` fails the
build otherwise.
"""

from __future__ import annotations

HEADER = """\
/*
    Generated by `bleck` from {origin}.
    Do not edit: rebuild the script instead.

    This is an evt script module. The arrays below are bytecode for Super Paper
    Mario's own script VM. `_prolog` hooks the game's sequence table; the entry
    script is handed to the scheduler when gameplay starts, and re-started after
    anything that resets evt state, such as a map change.

    Game functions are referenced by name and resolved by `elf2rel` against a
    symbol list, so no addresses appear here.
*/

typedef int s32;
typedef unsigned int u32;
typedef unsigned char u8;
"""

#: Lets a mod's own C run at load time without owning `_prolog`. Weak, so a
#: mod's own strong definition overrides it at link time.
MOD_HOOK = """/*
    A mod's own C may define `mod_prolog` to run when the module loads.

    This is a weak *definition* rather than a declaration, and the difference
    matters: a weak declaration leaves an undefined symbol, and `elf2rel` tries
    to resolve every undefined symbol against the game's list. `mod_prolog` is
    not a game function, so a script-only mod failed to build with
    "Missing 1 required symbol(s): mod_prolog". Defining it here means there is
    nothing left undefined, and a mod that supplies its own strong definition
    overrides this one at link time.

    `_prolog` stays owned by the generated code because it has to install the
    sequence hooks first -- see the comment below for why that ordering matters.

    Anything touching live engine state belongs in a sequence hook, not here:
    at load time the game is barely up. docs/hook-points.md has the timings.
*/
__attribute__((weak)) void mod_prolog(void)
{
}
"""


#: Writing PowerPC instructions at run time. Emitted into every module: a mod
#: declares the prototypes it wants and `--gc-sections` drops the rest.
CODE_PATCH = """/*
    Patching PowerPC instructions at run time.

    A store lands in the *data* cache. The instruction fetcher reads through
    the *instruction* cache and cannot see it, so a patched word looks correct
    to a debugger and does nothing until the line is pushed out and the matching
    instruction line invalidated: `dcbst`, `sync`, `icbi`, `isync`.

    `bleck_code_store` deliberately omits that. It exists so the flush can be
    measured against a control rather than assumed (D94).

    Unlike evt bytecode patching, which the VM reads as data (D89), this is the
    only route to intercepting a C function -- `evt_door_set_door_descs` among
    them (D93).
*/

#define BLECK_CODE_OK 0
#define BLECK_CODE_ALIGN 1
#define BLECK_CODE_RANGE 2

/* Unconditional branch, I-form: opcode 18, then a 24-bit word displacement. */
#define BLECK_CODE_BRANCH 0x48000000U
#define BLECK_CODE_DISP 0x03FFFFFCU

/* The displacement field is 26 bits signed, so roughly +/-32 MB. */
#define BLECK_CODE_MAX 0x01FFFFFC
#define BLECK_CODE_MIN (-0x02000000)

/* Store only, no flush. For measuring the flush, not for shipping. */
void bleck_code_store(void *at, u32 word)
{
    *(volatile u32 *) at = word;
}

/* Push the data line to memory, then invalidate the instruction line. */
void bleck_code_flush(void *at)
{
    __asm__ __volatile__("dcbst 0,%0\\n\\t"
                         "sync\\n\\t"
                         "icbi 0,%0\\n\\t"
                         "isync"
                         :
                         : "r"(at)
                         : "memory");
}

void bleck_code_write(void *at, u32 word)
{
    bleck_code_store(at, word);
    bleck_code_flush(at);
}

/*
    Encode `b to` as it would sit at `from`.

    An out-of-range displacement is refused, not truncated: masking it would
    emit a perfectly valid branch to somewhere else entirely, which is the
    failure this project keeps having to design out.
*/
s32 bleck_code_branch(const void *from, const void *to, u32 *out)
{
    s32 delta = (s32) ((const char *) to - (const char *) from);

    if ((((u32) from | (u32) to) & 3u) != 0)
        return BLECK_CODE_ALIGN;
    if (delta > BLECK_CODE_MAX || delta < BLECK_CODE_MIN)
        return BLECK_CODE_RANGE;
    *out = BLECK_CODE_BRANCH | ((u32) delta & BLECK_CODE_DISP);
    return BLECK_CODE_OK;
}

/* Encode, write and flush. Nothing is written unless the encode succeeded. */
s32 bleck_code_hook(void *at, const void *to)
{
    u32 word = 0;
    s32 status = bleck_code_branch(at, to, &word);

    if (status != BLECK_CODE_OK)
        return status;
    bleck_code_write(at, word);
    return BLECK_CODE_OK;
}
"""


#: Running C++ global constructors. Emitted only for a mod with C++ sources, so
#: a C-only module's generated source is unchanged.
CTOR_BLOCK = """
/*
    C++ global constructors.

    A global object's constructor is not something anything calls: the compiler
    puts a pointer to it in `.ctors` and expects a runtime to walk that table.
    A REL has no such runtime, so `_prolog` walks it and the markers below give
    it bounds -- a partially-linked object has no `__CTOR_LIST__`.

    Why the bracketing holds: devkitPPC links through `libogc_common.ld`, whose
    `.ctors` output takes plain `.ctors` inputs in link order and then
    `SORT_BY_NAME(.ctors.*)`, so the end marker lands last however many sources
    contributed. The `KEEP()` there is also what stops --gc-sections dropping
    the table. `toolchain._check_ctor_walk` re-measures this on the linked ELF
    rather than trusting it.

    Order across translation units is unspecified, exactly as in any C++
    program. Within one, GCC emits a single initialiser that calls them in
    declaration order.
*/

typedef void (*BleckCtor)(void);

__attribute__((section(".ctors"), used, aligned(4)))
static BleckCtor bleck_ctors_start[1] = {0};

__attribute__((section(".ctors.zzz_bleck_end"), used, aligned(4)))
static BleckCtor bleck_ctors_end[1] = {0};

static void bleck_run_ctors(void)
{
    BleckCtor *entry;
    BleckCtor *end;

    /*
        Laundered through empty asm so the optimiser cannot fold the comparison.
        These are two distinct objects to the compiler; only the linker makes
        them the ends of one table, so a constant-folded `start + 1 >= end`
        would legally delete the whole loop.
    */
    __asm__("" : "=r"(entry) : "0"(bleck_ctors_start + 1));
    __asm__("" : "=r"(end) : "0"(bleck_ctors_end));

    /* Zeroes are alignment padding between contributions, not initialisers. */
    for (; entry < end; entry++)
        if (*entry != 0)
            (*entry)();
}
"""

#: `PLAIN_PROLOG` for a C++ mod with nothing to schedule.
PLAIN_CTOR_PROLOG = """
void _prolog(void)
{
    bleck_run_ctors();
    mod_prolog();
}
"""

#: Running a script when a named map is reached.
#: ⛔ Patching `MapData.initScript` deadlocks the map loader (D51); the sequence
#: hook watches the destination instead.
MAP_BLOCK = """
/*
    Map hooks.

    The game announces where it is going: during a map change, `seqWork.p0`
    holds the destination map's name. So arriving somewhere is observable
    without touching the game's own data at all -- the sequence hook notes the
    name on the way in, and starts the script once gameplay resumes.

    RULED OUT: patching `MapData.initScript` to chain the map's own script.
    It deadlocks -- the load freezes partway and never completes, whether the
    original is spawned blocking or detached. Measured, not guessed; see D51.

    Both halves of what is used instead are already proven: `evtEntry` from
    `seq_data[SEQ_GAME].main` is exactly how every bleck script starts (D43),
    and reading `seqWork.p0` during a map change is how the destination was
    identified in the first place (D47).
*/

typedef struct
{{
    s32 seq;
    s32 stage;
    const char *p0;
    const char *p1;
}} SeqWork;

extern SeqWork seqWork;

#define BLECK_SEQ_MAPCHANGE 3
#define BLECK_MAP_COUNT {count}
{tables}
static const char *const bleck_map_names[BLECK_MAP_COUNT] = {{
{name_list}}};

static const s32 *const bleck_map_scripts[BLECK_MAP_COUNT] = {{
{script_list}}};

/*
    Which maps are waiting to start, one bit each. Set while the map change is
    still in flight and consumed when gameplay resumes, because that is the
    moment evt is alive again -- a script started during the change would be
    torn down with the rest of evt state.
*/
static u32 bleck_map_pending = 0;

/* By hand: the module links -nostdlib, so there is no strcmp to call. */
static u32 bleck_same_name(const char *a, const char *b)
{{
    u32 i;

    if (a == 0 || b == 0)
        return 0;
    for (i = 0; a[i] != 0; i++)
        if (a[i] != b[i])
            return 0;
    return b[i] == 0;
}}

static void bleck_maps_on_seq(u32 seq)
{{
    u32 i;

    if (seq == BLECK_SEQ_MAPCHANGE)
    {{
        for (i = 0; i < BLECK_MAP_COUNT; i++)
            if (bleck_same_name(seqWork.p0, bleck_map_names[i]))
                bleck_map_pending |= (1 << i);
        return;
    }}

    if (seq != BLECK_SEQ_GAME || bleck_map_pending == 0)
        return;

    for (i = 0; i < BLECK_MAP_COUNT; i++)
    {{
        if (bleck_map_pending & (1 << i))
        {{
            bleck_map_pending &= ~(1 << i);
            evtEntry(bleck_map_scripts[i], 0, 0);
        }}
    }}
}}
"""

#: One map's name. The script it starts is referenced by the table below.
MAP_TABLE = """
static const char {prefix}name_{index}[] = {name};
"""

#: The on-screen label naming the loaded mod. Call order mirrors
#: `spm-rel-loader`: start, style, measure, draw -- before the real sequence
#: main runs.
BANNER_BLOCK = """
/*
    Naming the loaded mod on screen.

    Text is drawn in screen space, which is centred with y increasing upward:
    `spm-rel-loader` centres a string with `x = -(width / 2)` and places it near
    the top of the title screen with `y = 200`. So the visible area is roughly
    x -320..320 and y -240..240, and the bottom-right corner is (+320, -240).
    The margins below back off from that corner far enough to survive overscan.

    `FontGetMessageWidth` measures the string so it can be right-aligned rather
    than positioned by guesswork, which also keeps a long mod name on screen.
*/

extern void FontDrawStart(void);
extern void FontDrawEdge(void);
extern void FontDrawColor(u8 *color);
extern void FontDrawScale(float scale);
extern void FontDrawNoiseOff(void);
extern void FontDrawRainbowColorOff(void);
extern void FontDrawString(float x, float y, const char *text);
extern unsigned short FontGetMessageWidth(const char *text);

#define BLECK_BANNER_RIGHT 296.0f
#define BLECK_BANNER_BOTTOM (-200.0f)
#define BLECK_BANNER_SCALE 0.6f

static const char bleck_banner_text[] = {text};

/* wii/gx.h GXColor, four bytes. Not const: FontDrawColor overwrites alpha. */
static u8 bleck_banner_color[4] = {{255, 255, 255, 255}};

/* Which sequences draw it. .rodata, so the loader's bss handling is moot. */
static const u8 bleck_banner_on[BLECK_SEQ_COUNT] = {{{flags}}};

static void bleck_draw_banner(void)
{{
    float width;

    FontDrawStart();
    FontDrawEdge();
    FontDrawColor(bleck_banner_color);
    FontDrawScale(BLECK_BANNER_SCALE);
    FontDrawNoiseOff();
    FontDrawRainbowColorOff();

    width = (float) FontGetMessageWidth(bleck_banner_text) * BLECK_BANNER_SCALE;
    FontDrawString(BLECK_BANNER_RIGHT - width, BLECK_BANNER_BOTTOM,
                   bleck_banner_text);
}}
"""

#: Typedefs and the saved originals, needed by anything wanting a per-frame hook.
SEQ_TABLE = """
/*
    Hooking the game's sequence table.

    `_prolog` runs the instant the loader links this module, far too early to
    hand anything to the script scheduler: the evt manager is not initialised
    yet, so `evtEntry` there does nothing at all. Hooking
    `seq_data[SEQ_GAME].init` does not work either. Both were measured, not
    guessed -- D38 and D40.

    What does work is `seq_data[SEQ_GAME].main`, verified by reading the running
    game's memory from outside the emulator: the script is created and then runs
    once per frame (D43).
*/

typedef void(SeqFunc)(void *);

typedef struct
{
    SeqFunc *init;
    SeqFunc *main;
    SeqFunc *exit;
} SeqDef;

/* Resolved by name from the symbol list, like everything else here. */
extern SeqDef seq_data[];

/* spm/seqdrv.h: LOGO 0, TITLE 1, GAME 2, MAPCHANGE 3, GAMEOVER 4, LOAD 5 */
#define BLECK_SEQ_COUNT 6
#define BLECK_SEQ_GAME 2

/*
    Deliberately initialised to non-zero values so these land in .data rather
    than .bss. The loader allocates this module's bss but nothing documents
    whether it zeroes it, and depending on that would be a silent hazard.
*/
static SeqFunc *bleck_real_main[BLECK_SEQ_COUNT] = {
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
    (SeqFunc *) 1, (SeqFunc *) 1, (SeqFunc *) 1,
};
"""

#: Starting the entry script, and keeping it started.
SCRIPT_START = """
/*
    A script does not survive a map change (D43). evt state is torn down and
    rebuilt, and a script started once simply stops. So rather than starting
    once, every sequence other than gameplay re-arms a flag and gameplay starts
    the script whenever it is armed. That covers map changes, game overs and
    loads without needing to know which of them resets evt.
*/

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{
    if (seq != BLECK_SEQ_GAME)
    {
        bleck_needs_start = 1;
        return;
    }
    if (bleck_needs_start)
    {
        bleck_needs_start = 0;
        evtEntry(%s, 0, 0);
    }
}
"""

#: Booting straight into a chosen map. Fires once on the first frame of
#: gameplay; re-arming it like `SCRIPT_START` would trap the game on that map.
BOOT_BLOCK = """
/*
    Booting into a map.

    An unattended boot reaches exactly two maps -- aa4_01 then ls4_12, the
    attract demo -- and controller input cannot be injected (D48), so every
    other map used to need a human. This starts a script on the first frame of
    gameplay that asks the game to go somewhere else instead (D52).

    Note what this does *not* do: it does not try to redirect the first map
    load, which would be faster. The game is asked to change maps through its
    own `evt_seq_mapchange`, exactly as a door would, so arriving here is the
    same arrival the game performs everywhere else. Overwriting `seqWork.p0`
    before the loader reads it is the obvious shortcut and is untested; D51 is
    what happens when the map loader is handed something it did not expect.

    `bleck_boot_pending` starts at 1 rather than 0 so it lands in .data. The
    loader allocates this module's bss but nothing documents whether it zeroes
    it, and a boot map that fired only on some builds would be a miserable bug.
*/

static u32 bleck_boot_pending = 1;

static void bleck_boot_on_seq(u32 seq)
{{
    if (seq != BLECK_SEQ_GAME || bleck_boot_pending == 0)
        return;
    bleck_boot_pending = 0;
    evtEntry({script}, 0, 0);
}}
"""

#: Starting a script when a button combination is pressed. ✅ The read path is
#: measured: `WpadWork.statuses` at `+0x6C`, newest sample first, with
#: `KPADStatus.buttonsHeld` as its first field (D67, D68).
COMBO_BLOCK = """
/*
    Button combinations.

    The game reads its own controller every frame, so a mod can read the same
    state. NOTE: This is not what D48 ruled out -- that was about *injecting* input
    into Dolphin from outside, for unattended tests, and says nothing about the
    game's own input. Conflating the two closed off this feature for weeks.

    Layout, all from spm-headers and confirmed against a running game:
      wpadGetWork()            spm/wpadmgr.h, returns WpadWork *
      WpadWork.statuses        +0x6C, [controller][age], newest age is 0
      KPADStatus.buttonsHeld   +0x00, and KPADStatus is 0x84 bytes

    NOTE: Masks are tested with `(held & mask) == mask`, never `held == mask`.
    Bit 31 of `buttonsHeld` flips between frames while the controller is
    untouched -- measured in D67 -- so an equality test would match on roughly
    half the frames and read as flaky hardware.

    Edge-triggered: a combination fires once when it becomes held, not sixty
    times a second while it stays held.
*/

extern void *wpadGetWork(void);

#define BLECK_WPAD_STATUSES 0x6C
#define BLECK_COMBO_COUNT {count}

static const u32 bleck_combo_masks[BLECK_COMBO_COUNT] = {{
{masks}}};

static const s32 *const bleck_combo_scripts[BLECK_COMBO_COUNT] = {{
{scripts}}};

/*
    Which combinations were held last frame, one bit each.

    Starts all-ones for two reasons: it is non-zero, so it lands in .data rather
    than .bss whose zeroing the loader does not document -- and it means every
    combination counts as already-held until it has been seen released. A button
    held while the game boots therefore cannot fire anything.
*/
static u32 bleck_combo_down = 0xFFFFFFFFu;

static u32 bleck_buttons_held(void)
{{
    u8 *work = (u8 *) wpadGetWork();

    /* Null before wpadInit has run; reading through it would fault. */
    if (work == 0)
        return 0;
    return *(volatile u32 *) (work + BLECK_WPAD_STATUSES);
}}

static void bleck_combos_on_seq(u32 seq)
{{
    u32 held, i, bit;

    /* evtEntry needs the script VM, which needs gameplay. Watching earlier is
       tempting and is what hung the game in D65. */
    if (seq != BLECK_SEQ_GAME)
        return;

    held = bleck_buttons_held();
    for (i = 0; i < BLECK_COMBO_COUNT; i++)
    {{
        bit = 1u << i;
        if ((held & bleck_combo_masks[i]) == bleck_combo_masks[i])
        {{
            if ((bleck_combo_down & bit) == 0)
            {{
                bleck_combo_down |= bit;
                evtEntry(bleck_combo_scripts[i], 0, 0);
            }}
        }}
        else
        {{
            bleck_combo_down &= ~bit;
        }}
    }}
}}
"""

#: Starting several mods' entry scripts, when a disc merges more than one.
#: `SCRIPT_START` is kept alongside so a one-mod disc emits an unchanged file.
SCRIPT_START_MANY = """
/*
    Entry scripts, one per mod sharing this module.

    Each mod's `main` is started, and all of them are re-armed together: they
    are all torn down by the same map change, so there is nothing to track
    separately (D43).
*/

#define BLECK_ENTRY_COUNT {count}

static const s32 *const bleck_entries[BLECK_ENTRY_COUNT] = {{
{entries}}};

static u32 bleck_needs_start = 1;

static void bleck_start_entry(u32 seq)
{{
    u32 i;

    if (seq != BLECK_SEQ_GAME)
    {{
        bleck_needs_start = 1;
        return;
    }}
    if (bleck_needs_start)
    {{
        bleck_needs_start = 0;
        for (i = 0; i < BLECK_ENTRY_COUNT; i++)
            evtEntry(bleck_entries[i], 0, 0);
    }}
}}
"""

#: Replacing one instruction of a vanilla `evt` script with a call into this
#: module. ✅ Measured (D89, D90): the VM read the mutated bytecode, called into
#: `mod.rel` and the map ran normally for 90 s.
PATCH_BLOCK = """
/*
    evt script patches.

    A vanilla script's instruction is overwritten in place with a `USER_FUNC`
    calling a function in the mod's own sources. The script's *pointer* is left
    alone -- repointing it is what deadlocked the map loader in D51, and is
    still ruled out. Mutating the bytecode it already refers to creates no new
    `EvtEntry`, so that condition never arises (D87, D89).

    SAME SIZE, ANY SIZE. An instruction is a header declaring M argument words,
    then those M words. The replacement is a USER_FUNC header declaring the same
    M, then the function pointer, then the original's words 2..M carried through
    untouched. M is read out of the header the guard just matched, so the
    replacement cannot be a different length -- which is what keeps every label
    where it was, and `jumptable[]` is cached per `EvtEntry` when a script
    starts.

    At M = 1 that is `USER_FUNC f` with no arguments and the original's single
    argument is lost; at M = 4 -- an item script's opening
    `USER_FUNC g, a, b, c` -- it redirects the call and keeps its arguments.

    The hook reads those carried-through arguments from its EvtEntry:
    `pCurData` (spm/evtmgr.h +0x14) points at the instruction's argument words,
    and `curDataLength` (+0x09) says how many there are.

    THE GUARD IS THE POINT. The word at the offset must be the header the
    manifest named, or nothing is written. A wrong offset then costs a status
    of REFUSED rather than an undiagnosable freeze.

    NOTE: No cache flush. This is bytecode read as *data*, unlike patching PowerPC
    instructions, which needs dcbst/sync/icbi.

    NOTE: Applied once, at load. The mutation therefore lasts the whole session,
    including maps entered later; it is not re-applied per arrival.

    A mod reads the outcome with:

        extern unsigned int bleck_patch_status[];
        extern unsigned int bleck_patch_shared[];
*/

/*
    USER_FUNC is opcode 0x5C, and a header's top half is its argument count --
    `EVT_HELPER_CMD(n, 92)` in spm-headers/mod/evt_cmd.h. The count is taken
    from the matched word, so the replacement is the same size by construction.
*/
#define BLECK_USER_FUNC 0x005Cu
#define BLECK_ARGC_MASK 0xFFFF0000u

#define BLECK_PATCH_MAP 0
#define BLECK_PATCH_ITEM 1

/* bleck_patch_status[] values. */
#define BLECK_PATCH_PENDING 1
#define BLECK_PATCH_APPLIED 2
#define BLECK_PATCH_REFUSED 3
#define BLECK_PATCH_NO_SCRIPT 4
#define BLECK_PATCH_NOT_FOUND 5

/* bleck_patch_shared[] where nothing counted. */
#define BLECK_PATCH_UNCOUNTED 0xFFFFFFFFu

#define BLECK_PATCH_COUNT {count}

typedef struct
{{
    u32 kind;
    const char *target;
    s32 itemId;
    u32 at;
    u32 expect;
    const void *call;
}} BleckPatch;
{decls}
static const BleckPatch bleck_patches[BLECK_PATCH_COUNT] = {{
{rows}}};

/*
    Not static: a mod's own C reads this to answer "did my patch take" without a
    debugger. Initialised to PENDING rather than 0 so it lands in .data -- the
    loader allocates this module's bss but does not document zeroing it.
*/
u32 bleck_patch_status[BLECK_PATCH_COUNT] = {{
{pending}}};

/*
    How many places point at the script each patch hit, or UNCOUNTED where
    nothing counted it.

    WARNING: item use scripts are shared. 22 distinct scripts across the 33
    table entries (D91), so a value above 1 means this patch changed other items
    too. Counted even when the patch is refused, so the number is readable
    either way.
*/
u32 bleck_patch_shared[BLECK_PATCH_COUNT] = {{
{uncounted}}};

const u32 bleck_patch_count = BLECK_PATCH_COUNT;
{resolvers}
static void bleck_apply_patches(void)
{{
    u32 i;
    u32 *script;
    const BleckPatch *patch;

    for (i = 0; i < BLECK_PATCH_COUNT; i++)
    {{
        patch = &bleck_patches[i];
        script = 0;
{resolve}
        if (script == 0)
        {{
            bleck_patch_status[i] = BLECK_PATCH_NO_SCRIPT;
            continue;
        }}
        if (script[patch->at] != patch->expect)
        {{
            bleck_patch_status[i] = BLECK_PATCH_REFUSED;
            continue;
        }}
        /* Header, then the pointer. Words at + 2 .. at + argc are the
           original's own arguments and are deliberately left alone. */
        script[patch->at] = (patch->expect & BLECK_ARGC_MASK) | BLECK_USER_FUNC;
        script[patch->at + 1] = (u32) patch->call;
        bleck_patch_status[i] = BLECK_PATCH_APPLIED;
    }}
}}
"""

#: Replacing a game function outright with one of the mod's own. ✅ The
#: mechanism is measured (D94): a branch written over `npcDispMain` at
#: `mod_prolog` fired 62,480 times across 90 s of gameplay.
HOOK_BLOCK = """
/*
    Function hooks.

    A game function's first instruction is overwritten with `b <mod function>`,
    so every call into it lands in the mod instead. `bleck_code_hook` encodes,
    writes and flushes; the flush is not a formality, and D94 measured a patch
    without one doing nothing at all while looking correct in memory.

    WHICH MODE A ROW IS lives in its comment, not in the table: the branch is
    the same either way, and only its destination differs.

      replace   the branch lands on the mod's function, and for the rest of the
                session THE ORIGINAL NEVER RUNS. The mod's function is the whole
                implementation and must return what the caller expects.
      before    the branch lands on a generated wrapper, which calls the mod's
                function and then the original.
      after     the same wrapper, in the other order.

    Both wrapped forms return the ORIGINAL's value, so a handler cannot change
    what the caller receives by returning something. They reach the original by
    restoring this row's `expect` for the duration of the call (D96, D97), which
    is why interception needs a derived guard and `replace` does not.

    THE GUARD IS DERIVED, NOT DECLARED. Nobody can reasonably know the
    instruction word at a function's entry, so `bleck` reads it out of the base
    disc's `main.dol` at build time and generates it here. If the running game
    does not have that word, nothing is written -- which turns a wrong address
    or the wrong game version into a clean refusal instead of a branch into the
    middle of something else.

    An address the DOL does not map -- a REL address, say -- has no derived
    guard. Those rows carry `guarded = 0` and install unguarded; the build warns
    and says why. Nothing here is ever guarded against a word bleck did not
    actually read.

    NOTE: Installed once, at `_prolog`, before `mod_prolog`. The DOL's text is
    resident for the whole session, so the branch lasts it too.

    A mod reads the outcome with:

        extern unsigned int bleck_hook_status[];
*/

/* bleck_hook_status[] values. */
#define BLECK_HOOK_PENDING 1
#define BLECK_HOOK_INSTALLED 2
#define BLECK_HOOK_REFUSED 3
#define BLECK_HOOK_MISALIGNED 4
#define BLECK_HOOK_OUT_OF_RANGE 5

#define BLECK_HOOK_COUNT {count}

typedef struct
{{
    void *at;
    u32 expect;
    u32 guarded;
    const void *call;
}} BleckFunctionHook;
{decls}
static const BleckFunctionHook bleck_function_hooks[BLECK_HOOK_COUNT] = {{
{rows}}};

/*
    Not static: a mod's own C reads this to tell installed from refused without
    a debugger. Initialised to PENDING rather than 0 so it lands in .data -- the
    loader allocates this module's bss but does not document zeroing it.
*/
u32 bleck_hook_status[BLECK_HOOK_COUNT] = {{
{pending}}};

const u32 bleck_hook_count = BLECK_HOOK_COUNT;

static void bleck_install_hooks(void)
{{
    u32 i;
    s32 status;
    const BleckFunctionHook *hook;

    for (i = 0; i < BLECK_HOOK_COUNT; i++)
    {{
        hook = &bleck_function_hooks[i];
        if (hook->guarded && *(volatile u32 *) hook->at != hook->expect)
        {{
            bleck_hook_status[i] = BLECK_HOOK_REFUSED;
            continue;
        }}
        /* Encodes first and writes nothing on a bad encoding, so an
           out-of-range branch costs a status rather than a wild jump. */
        status = bleck_code_hook(hook->at, hook->call);
        if (status == BLECK_CODE_ALIGN)
            bleck_hook_status[i] = BLECK_HOOK_MISALIGNED;
        else if (status == BLECK_CODE_RANGE)
            bleck_hook_status[i] = BLECK_HOOK_OUT_OF_RANGE;
        else
            bleck_hook_status[i] = BLECK_HOOK_INSTALLED;
    }}
}}
"""

#: The hooked game function, declared for its address only -- exactly as game
#: functions called by USER_FUNC are. No address is written for a named symbol;
#: `elf2rel` binds it, so the symbol list stays the one source of truth.
HOOK_TARGET = "extern void {name}(void);"

#: The mod's own replacement, declared for its address only.
HOOK_CALL = "extern void {name}(void);"

#: Resolving `map:<name>`. Emitted only when a map patch is declared, so an
#: item-only module leaves `mapDataPtr` unreferenced.
PATCH_MAP_RESOLVER = """
extern void *mapDataPtr(const char *name);

/* spm/map_data.h: MapData.initScript. Populated and stable at _prolog, for maps
   never loaded as much as for loaded ones -- measured, D88. */
#define BLECK_MAP_INIT_SCRIPT 0x18

static u32 *bleck_map_init_script(const char *name)
{
    unsigned char *data = (unsigned char *) mapDataPtr(name);

    if (data == 0)
        return 0;
    return *(u32 **) (data + BLECK_MAP_INIT_SCRIPT);
}
"""

#: The one line `bleck_apply_patches` needs for map patches.
PATCH_MAP_RESOLVE = """        if (patch->kind == BLECK_PATCH_MAP)
            script = bleck_map_init_script(patch->target);
"""

#: Resolving `item:<id>`. ✅ The table's shape and contents are measured (D91);
#: 🔶 nothing has yet observed a patched item script being *entered*.
PATCH_ITEM_RESOLVER = """
/*
    Item use scripts.

    `itemEventDataTable` is 33 entries of {itemId, useScript, useMsgName} living
    in the DOL's own static data, so the pointer is valid at _prolog with no map
    resident -- an easier target than a map's init script (D91).

    RULED OUT: calling `getItemUseEvt`. item_event_data.h says it returns "a
    fallback if the item isn't in there", so an id the table does not hold would
    silently patch a script shared by everything. The table is walked instead,
    and an absent id gets its own status.

    WARNING: entries share scripts -- 22 distinct across 33. Patching one item
    id can change several, so the sharers are counted into
    bleck_patch_shared[].
*/

#define BLECK_ITEM_COUNT 33

typedef struct
{
    s32 itemId;
    u32 *useScript;
    const char *useMsgName;
} BleckItemEventData;

extern BleckItemEventData itemEventDataTable[];

static s32 bleck_item_index(s32 itemId)
{
    s32 i;

    for (i = 0; i < BLECK_ITEM_COUNT; i++)
        if (itemEventDataTable[i].itemId == itemId)
            return i;
    return -1;
}

static u32 bleck_item_sharers(const u32 *script)
{
    s32 i;
    u32 sharers = 0;

    for (i = 0; i < BLECK_ITEM_COUNT; i++)
        if (itemEventDataTable[i].useScript == script)
            sharers++;
    return sharers;
}
"""

#: The item arm of `bleck_apply_patches`. "No such id" is its own status: it is
#: a different mistake from "the guard refused".
PATCH_ITEM_RESOLVE = """        if (patch->kind == BLECK_PATCH_ITEM)
        {
            s32 index = bleck_item_index(patch->itemId);

            if (index < 0)
            {
                bleck_patch_status[i] = BLECK_PATCH_NOT_FOUND;
                continue;
            }
            script = itemEventDataTable[index].useScript;
            bleck_patch_shared[i] = bleck_item_sharers(script);
        }
"""

#: One patched script's name, held out of the table so it is a real string.
PATCH_TARGET = "static const char bleck_patch_target_{index}[] = {name};"

#: The mod's own hook, declared for its address only -- exactly as game
#: functions called by USER_FUNC are declared.
PATCH_CALL = "extern void {name}(void);"

#: A banner above each mod's own section of the merged module.
MOD_SECTION = """
/* ------------------------------------------------------------------------
   {name}
   ------------------------------------------------------------------------ */
"""

#: One trampoline per sequence, because the game passes no index of its own.
SEQ_STUBS = """
static void bleck_seq0(void *w) { bleck_after_seq(0, w); }
static void bleck_seq1(void *w) { bleck_after_seq(1, w); }
static void bleck_seq2(void *w) { bleck_after_seq(2, w); }
static void bleck_seq3(void *w) { bleck_after_seq(3, w); }
static void bleck_seq4(void *w) { bleck_after_seq(4, w); }
static void bleck_seq5(void *w) { bleck_after_seq(5, w); }

static SeqFunc *const bleck_hooks[BLECK_SEQ_COUNT] = {
    bleck_seq0, bleck_seq1, bleck_seq2,
    bleck_seq3, bleck_seq4, bleck_seq5,
};
"""

#: Installs the sequence hooks, as the body of `_prolog`.
SEQ_INSTALL = """    u32 i;

    for (i = 0; i < BLECK_SEQ_COUNT; i++)
    {
        bleck_real_main[i] = seq_data[i].main;
        seq_data[i].main = bleck_hooks[i];
    }

"""

#: For a mod with nothing to schedule and no map to watch.
PLAIN_PROLOG = """
void _prolog(void)
{
    mod_prolog();
}
"""

ENTRY_POINTS = """
void _epilog(void)
{
}

void _unresolved(void)
{
}
"""
