#!/usr/bin/env python3
"""Generate the language reference pages that must never be written by hand.

Two pages come out of data `bleck` already owns:

    docs-site/language/builtins.md   443 game functions, from catalog.json
    docs-site/language/storage.md    the storage classes, from bleck/script/evt.py

⚠️ **Regenerate these; do not edit them.** A hand-maintained list of 443
functions is wrong the first time the catalog is regenerated, and a stale
reference is worse than no reference -- it is believed. Both files carry a
generated-header saying so.

    uv run python scripts/dump_builtins.py
    uv run python scripts/dump_builtins.py --check    # CI: fail if stale

`--check` is what keeps them honest: it regenerates into memory and compares,
so a catalog change that was not followed by a docs regeneration fails the
build rather than shipping a quietly-wrong page.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bleck.script import evt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "bleck" / "script" / "catalog.json"
BUILTINS_PAGE = ROOT / "docs-site" / "language" / "builtins.md"
STORAGE_PAGE = ROOT / "docs-site" / "language" / "storage.md"

BANNER = (
    "<!-- Generated by scripts/dump_builtins.py. Do not edit by hand:\n"
    "     run `uv run python scripts/dump_builtins.py` instead. -->\n"
)

#: Modules whose names say what they cover, grouped so the page reads as
#: something other than an alphabetical wall.
GROUPS = {
    "The player": ("evt_mario", "evt_pouch", "evt_party", "evt_fairy"),
    "The world": ("evt_map", "evt_mapobj", "evt_mobj", "evt_npc", "evt_item"),
    "Presentation": ("evt_cam", "evt_snd", "evt_msg", "evt_eff", "evt_window", "evt_lyt"),
    "Flow and sequencing": ("evt_seq", "evt_frame", "evt_sub", "evt_case", "evt_shop"),
}


@dataclass(frozen=True)
class Builtin:
    """One callable game function, as the catalog records it."""

    name: str
    module: str
    arity: int | None
    signature: str

    def row(self) -> str:
        """⚠️ `arity` is None for a function whose argument count is unrecorded.

        Those cannot be argument-checked at compile time, so the page says so
        rather than printing a confident 0.
        """
        count = "?" if self.arity is None else str(self.arity)
        shown = self.signature or f"{self.name}({', '.join(['?'] * (self.arity or 0))})"
        return f"| `{self.name}` | {count} | `{shown}` |"


def load() -> list[Builtin]:  # pylint: disable=container-return
    raw = json.loads(CATALOG.read_text(encoding="utf-8"))
    return [
        Builtin(
            name=entry["name"],
            module=entry.get("module", ""),
            arity=None if entry.get("arity") is None else int(entry["arity"]),
            signature=entry.get("signature", ""),
        )
        for entry in raw["builtins"]
    ]


def _group_of(module: str) -> str:
    for title, modules in GROUPS.items():
        if module in modules:
            return title
    return "Everything else"


def builtins_page(entries: list[Builtin]) -> str:
    by_module: dict[str, list[Builtin]] = defaultdict(list)
    for entry in entries:
        by_module[entry.module].append(entry)

    documented = sum(1 for entry in entries if entry.signature)
    unknown = sum(1 for entry in entries if entry.arity is None)
    out = [
        BANNER,
        "\n# Built-in functions\n\n",
        f"Every game function a script can call: **{len(entries)}** across "
        f"**{len(by_module)}** modules. {documented} carry a full signature "
        "taken from the decompilation; the rest are known by name and argument "
        "count only.\n\n",
        f"⚠️ **{unknown} have no recorded argument count** and are shown with "
        "`?`. A call to one of those cannot be argument-checked.\n\n"
        if unknown
        else "",
        '!!! warning "Argument counts are checked; types are not"\n\n'
        "    `bleck` rejects a call with the wrong number of arguments at "
        "compile time. It cannot check what those arguments *mean* -- passing "
        "a map name where an NPC name belongs compiles cleanly and misbehaves "
        "in game.\n\n",
        "Find one from the command line, which searches the same catalog:\n\n",
        "```bash\nuv run bleck script builtins --search coin\n```\n",
    ]

    ordered = list(GROUPS) + ["Everything else"]
    grouped: dict[str, list[str]] = defaultdict(list)
    for module in sorted(by_module):
        grouped[_group_of(module)].append(module)

    for title in ordered:
        modules = grouped.get(title)
        if not modules:
            continue
        out.append(f"\n## {title}\n")
        for module in modules:
            found = sorted(by_module[module], key=lambda entry: entry.name)
            out.append(f"\n### `{module}` <small>{len(found)} functions</small>\n")
            out.append("\n| Function | Args | Signature |\n|---|---|---|\n")
            out.append("\n".join(entry.row() for entry in found) + "\n")
    return "".join(out)


def storage_page() -> str:
    out = [
        BANNER,
        "\n# Storage classes\n\n",
        "The evt VM has no memory model beyond a fixed set of numbered slots. "
        "A script reads and writes them directly, and **the numeric range of an "
        "operand is what says which class it belongs to** -- there is no tag "
        "byte.\n",
        "\n| Class | Slots | Survives a save? | What it is |\n|---|---|---|---|\n",
    ]
    for storage in evt.STORAGE_CLASSES:
        limit = str(storage.limit) if storage.limit else "unbounded"
        saved = "yes" if "persists" in storage.description else "no"
        what = storage.description.split(":", 1)[-1].split("(")[0].strip()
        out.append(f"| `{storage.name.lower()}[]` | {limit} | {saved} | {what} |\n")

    out.append(
        "\n"
        "```\n"
        "gw[3] = 1            -- shared between scripts, lost on reset\n"
        "lw[0] = lw[0] + 1    -- scratch, cleared when the script ends\n"
        "```\n"
        "\n"
        "!!! danger \"The saved classes are the game's own progression\"\n\n"
        "    `lsw`, `gsw`, `lswf` and `gswf` persist in the save file and are "
        "the same slots the game uses to track chapter progress, doors opened "
        "and items taken. Writing one can corrupt a playthrough. Use `gw` and "
        "`lw` unless you specifically intend to change saved state.\n"
        "\n"
        "!!! note \"Floats are fixed-point\"\n\n"
        f"    A float operand is stored as `value * {evt.FLOAT_SCALE:g}`, so it "
        "carries about three decimal places. Values outside the float window "
        "decode as pointers or plain integers instead, which is why the range "
        "-- not a type -- is what makes a float a float.\n"
    )
    return "".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the pages are out of date"
    )
    args = parser.parse_args(argv)

    entries = load()
    wanted = {BUILTINS_PAGE: builtins_page(entries), STORAGE_PAGE: storage_page()}

    stale = []
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT).as_posix()}")

    if stale:
        print("stale, regenerate with scripts/dump_builtins.py:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return 1
    if args.check:
        print(f"up to date ({len(entries)} builtins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
