"""Which doors a map has, and which of them a `door:` selector can reach.

⚠️ **"Door" means two different things**, and only one is patchable (D138):

| | | |
|---|---|---|
| `DoorDesc` | 0x58 | interact / init / move scripts. **`door:` reaches these** |
| `MapDoorDesc` | 0x20 | a destination, and **no scripts at all** |

Across the whole game that is **35** scriptable doors against **691** loading
zones, on 11 maps out of 368 — nearly all of them house doors in Flipside and
Flopside. A map with five visible doorways may expose none.

⚠️ **A `door:` index is a position in the array the map registers**, not an id
and nothing visible in game (D103). That is why this catalog exists: until it
did, the only way to learn a map's count was to guess and read a status word at
run time, which is how `mods/door-attended` came to carry a `door:he1_01:9`
patch that addressed nothing for weeks (D137).

Generated by `scripts/dump_doors.py` from a running game and committed, like the
map and NPC catalogs — the descriptor arrays are reached through pointers that
only exist at run time.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

CATALOG = Path(__file__).with_name("doorcatalog.json")


@dataclass(frozen=True)
class DoorScripts:
    """Which of a door's three script slots are filled."""

    interact: bool = False
    init: bool = False
    move: bool = False

    def names(self) -> list[str]:
        return [
            name
            for name, present in (
                ("interact", self.interact),
                ("init", self.init),
                ("move", self.move),
            )
            if present
        ]


@dataclass(frozen=True)
class Door:
    """One `DoorDesc` — a door with scripts, reachable by `door:<map>:<index>`."""

    index: int
    name: str = ""
    group: str = ""
    scripts: DoorScripts = field(default_factory=DoorScripts)

    def describe(self) -> str:
        which = ", ".join(self.scripts.names()) or "no scripts"
        where = f" in {self.group}" if self.group else ""
        return f"[{self.index}] {self.name or '?'}{where}  ({which})"


@dataclass(frozen=True)
class Zone:
    """One `MapDoorDesc` — a loading zone. **Nothing here can be patched.**"""

    index: int
    name: str = ""
    to_map: str = ""
    to_door: str = ""

    def describe(self) -> str:
        return f"[{self.index}] {self.name or '?'} -> {self.to_map or '?'}"


@dataclass(frozen=True)
class MapDoors:
    """Everything one map registers, of both kinds."""

    map_name: str
    doors: list[Door] = field(default_factory=list)
    zones: list[Zone] = field(default_factory=list)

    def door(self, index: int) -> Door | None:
        for found in self.doors:
            if found.index == index:
                return found
        return None


@dataclass(frozen=True)
class DoorCatalog:
    """Every map that registers a door of either kind.

    Empty when the catalog is missing. ⚠️ **Callers must treat empty as
    "unknown", never as "no map has doors"** — refusing every `door:` selector
    because a data file was not shipped would be worse than not checking.
    """

    maps: list[MapDoors] = field(default_factory=list)

    def __bool__(self) -> bool:
        return bool(self.maps)

    def find(self, map_name: str) -> MapDoors | None:
        for found in self.maps:
            if found.map_name == map_name:
                return found
        return None

    @property
    def scriptable(self) -> list[MapDoors]:
        """Only the maps with a `DoorDesc` — the ones `door:` can reach."""
        return [found for found in self.maps if found.doors]


@lru_cache(maxsize=1)
def catalog() -> DoorCatalog:
    """The committed catalog, read once."""
    if not CATALOG.is_file():
        return DoorCatalog()
    body = json.loads(CATALOG.read_text(encoding="utf-8"))
    return DoorCatalog(
        maps=[
            MapDoors(
                map_name=entry.get("map", ""),
                doors=[
                    Door(
                        index=door.get("index", 0),
                        name=door.get("name", ""),
                        group=door.get("group", ""),
                        scripts=DoorScripts(**door.get("scripts", {})),
                    )
                    for door in entry.get("doors", [])
                ],
                zones=[
                    Zone(
                        index=zone.get("index", 0),
                        name=zone.get("name", ""),
                        to_map=zone.get("to_map", ""),
                        to_door=zone.get("to_door", ""),
                    )
                    for zone in entry.get("zones", [])
                ],
            )
            for entry in body.get("maps", [])
        ]
    )


def selector_problem(map_name: str, index: int) -> str:
    """Why `door:<map_name>:<index>` can never match, or "" if it can.

    Returns a message rather than raising: the manifest layer owns its own error
    type and knows which field to name, and this module has no business
    importing it.

    ⚠️ **An absent catalog returns ""** -- unknown, not "no doors". Refusing
    every selector because a data file was not shipped would be worse than the
    silence this replaced.

    ⚠️ Two distinct answers, deliberately. Only 11 of 368 maps register a
    scriptable door, and the visible doorways are mostly loading zones with no
    scripts, so "you picked the wrong index" and "there is nothing here to pick"
    send someone to different places.
    """
    found = catalog()
    if not found:
        return ""
    entry = found.find(map_name)
    if entry is None or not entry.doors:
        zones = len(entry.zones) if entry else 0
        note = (
            f"\n  It registers {zones} loading zone(s), which carry a "
            f"destination and no scripts -- nothing for a patch to reach."
            if zones
            else ""
        )
        return (
            f"{map_name} registers no scriptable door, so "
            f"'door:{map_name}:{index}' can never match.{note}\n"
            f"  `bleck doors` lists the {len(found.scriptable)} map(s) that do."
        )
    if entry.door(index) is None:
        listed = ", ".join(str(door.index) for door in entry.doors)
        return (
            f"{map_name} has no door {index}. Its door(s) are: {listed}.\n"
            f"  An index is a position in the order the map registers them, "
            f"not an id. `bleck doors {map_name}` names each one."
        )
    return ""
